local addonName, MSC = ...
local L = {}
setmetatable(L, {
    __index = function(t, k)
        local v = tostring(k)
        rawset(t, k, v)
        return v
    end
})

MSC.L = L

-- =============================================================
-- ENGLISH (Default)
-- =============================================================

-- =============================================================
-- Init
-- =============================================================
L["|cff00ff00Sharpie's Gear Judge:|r Loaded %s"] = "|cff00ff00Sharpie's Gear Judge:|r Loaded %s"

-- =============================================================
-- Conflict Manager
-- =============================================================
L["Yes, Disable & Reload"] = "Yes, Disable & Reload"
L["No, Keep Both"] = "No, Keep Both"
L["|cff00FF00[SGJ]|r: Pawn settings not found yet."] = "|cff00FF00[SGJ]|r: Pawn settings not found yet."
L["|cff00FF00Sharpie's Gear Judge|r\n\nI see RestedXP is active.\n\nIt is currently showing its own gear tips.\n\nDo you want me to disable their **Item Upgrade** setting?"] = "|cff00FF00Sharpie's Gear Judge|r\n\nI see RestedXP is active.\n\nIt is currently showing its own gear tips.\n\nDo you want me to disable their **Item Upgrade** setting?"
L["|cff00FF00Sharpie's Gear Judge|r\n\nI see Zygor Guides is active.\n\nIt adds its own 'Gear Score' to tooltips.\n\nDo you want me to disable their **Auto Gear** system?"] = "|cff00FF00Sharpie's Gear Judge|r\n\nI see Zygor Guides is active.\n\nIt adds its own 'Gear Score' to tooltips.\n\nDo you want me to disable their **Auto Gear** system?"
L["|cff00FF00Sharpie's Gear Judge|r\n\nI see Pawn is active.\n\nFor conflict-free use, we recommend disabling **Pawn's Tooltip Upgrades** so they don't overlap with our Verdict.\n\nDisable Pawn tooltip info?"] = "|cff00FF00Sharpie's Gear Judge|r\n\nI see Pawn is active.\n\nFor conflict-free use, we recommend disabling **Pawn's Tooltip Upgrades** so they don't overlap with our Verdict.\n\nDisable Pawn tooltip info?"

-- =============================================================
-- Evaluator
-- =============================================================
L["Bag Item"] = "Bag Item"
L["Cap"] = "Cap"
L["Exp"] = "Exp"
L["Def"] = "Def"

-- Context Messages
L["|cffff0000(Not 2Hander)|r"] = "|cffff0000(Not 2Hander)|r"
L["|cff00ff00(w/ %s)|r"] = "|cff00ff00(w/ %s)|r"
L["|cffff0000(No OH found)|r"] = "|cffff0000(No OH found)|r"
L["|cffff0000(No MH found)|r"] = "|cffff0000(No MH found)|r"
L["|cff00ff00(Set Bonus %s)|r"] = "|cff00ff00(Set Bonus %s)|r"

-- Cap Warnings (Format Strings)
L[" |cffff0000(Cap %.1f %s)|r"] = " |cffff0000(Cap %.1f %s)|r"
L[" |cffff0000(Cap %.1f Def)|r"] = " |cffff0000(Cap %.1f Def)|r"

-- =============================================================
-- Database
-- =============================================================

-- 1. STAT NAMES (Short)
MSC.L["Resilience"] = "Resilience"
MSC.L["Haste"] = "Haste"
MSC.L["Spell Haste"] = "Spell Haste"
MSC.L["Expertise"] = "Expertise"
MSC.L["Armor Pen"] = "Armor Pen"
MSC.L["Spell Pen"] = "Spell Pen"
MSC.L["Feral AP"] = "Feral AP"
MSC.L["PvP Utility"] = "PvP Utility"
MSC.L["Armor"] = "Armor"
MSC.L["Agility"] = "Agility"
MSC.L["Strength"] = "Strength"
MSC.L["Intellect"] = "Intellect"
MSC.L["Spirit"] = "Spirit"
MSC.L["Stamina"] = "Stamina"
MSC.L["Health"] = "Health"
MSC.L["Mana"] = "Mana"
MSC.L["Spell Power"] = "Spell Power"
MSC.L["Healing"] = "Healing"
MSC.L["Mp5"] = "Mp5"
MSC.L["Hp5"] = "Hp5"
MSC.L["DPS"] = "DPS"
MSC.L["Attack Power"] = "Attack Power"
MSC.L["Ranged AP"] = "Ranged AP"
MSC.L["Crit"] = "Crit"
MSC.L["Spell Crit"] = "Spell Crit"
MSC.L["Hit"] = "Hit"
MSC.L["Spell Hit"] = "Spell Hit"
MSC.L["Crit (from Agi)"] = "Crit (from Agi)"
MSC.L["Spell Crit (from Int)"] = "Spell Crit (from Int)"
MSC.L["Defense"] = "Defense"
MSC.L["Dodge"] = "Dodge"
MSC.L["Parry"] = "Parry"
MSC.L["Block %"] = "Block %"
MSC.L["Block Value"] = "Block Value"
MSC.L["Shadow Dmg"] = "Shadow Dmg"
MSC.L["Fire Dmg"] = "Fire Dmg"
MSC.L["Frost Dmg"] = "Frost Dmg"
MSC.L["Arcane Dmg"] = "Arcane Dmg"
MSC.L["Nature Dmg"] = "Nature Dmg"
MSC.L["Holy Dmg"] = "Holy Dmg"
MSC.L["Shadow Res"] = "Shadow Res"
MSC.L["Fire Res"] = "Fire Res"
MSC.L["Frost Res"] = "Frost Res"
MSC.L["Nature Res"] = "Nature Res"
MSC.L["Arcane Res"] = "Arcane Res"
MSC.L["All Res"] = "All Res"
MSC.L["Speed"] = "Speed"
MSC.L["Weapon DPS"] = "Weapon DPS"
MSC.L["Wand DPS"] = "Wand DPS"

-- 2. UI LABELS / LEVELING SETS
MSC.L["Starter (1-20)"] = "Starter (1-20)"
MSC.L["Standard Leveling (21-40)"] = "Standard Leveling (21-40)"
MSC.L["Standard Leveling (41-51)"] = "Standard Leveling (41-51)"
MSC.L["Standard Leveling (52-59)"] = "Standard Leveling (52-59)"
MSC.L["Standard Leveling (Outland)"] = "Standard Leveling (Outland)"

-- 3. ENCHANTS & SCOPES
MSC.L["Mongoose"] = "Mongoose"
MSC.L["Sunfire"] = "Sunfire"
MSC.L["Soulfrost"] = "Soulfrost"
MSC.L["Executioner"] = "Executioner"
MSC.L["Major Spellpower"] = "Major Spellpower"
MSC.L["Major Healing"] = "Major Healing"
MSC.L["Sunfire (Healing)"] = "Sunfire (Healing)"
MSC.L["Major Intellect"] = "Major Intellect"
MSC.L["Savagery"] = "Savagery"
MSC.L["Major Agility"] = "Major Agility"
MSC.L["Greater Agility (2H)"] = "Greater Agility (2H)"
MSC.L["Spell Surge"] = "Spell Surge"
MSC.L["Potency"] = "Potency"
MSC.L["Crusader"] = "Crusader"
MSC.L["Fiery Weapon"] = "Fiery Weapon"
MSC.L["Weapon Dmg +5"] = "Weapon Dmg +5"
MSC.L["Spellpower +30"] = "Spellpower +30"
MSC.L["Healing +55"] = "Healing +55"
MSC.L["Unholy Weapon"] = "Unholy Weapon"
MSC.L["Major Strength (+15)"] = "Major Strength (+15)"
MSC.L["Lifestealing"] = "Lifestealing"
MSC.L["Lesser Striking (+3)"] = "Lesser Striking (+3)"
MSC.L["Icy Chill"] = "Icy Chill"
MSC.L["Agility +15"] = "Agility +15"
MSC.L["Major Striking (+4)"] = "Major Striking (+4)"
MSC.L["Superior Striking (+5)"] = "Superior Striking (+5)"
MSC.L["Greater Striking (+4)"] = "Greater Striking (+4)"
MSC.L["Striking (+3)"] = "Striking (+3)"
MSC.L["Lesser Striking (+2)"] = "Lesser Striking (+2)"
MSC.L["Minor Striking (+1)"] = "Minor Striking (+1)"
MSC.L["Demonslaying"] = "Demonslaying"
MSC.L["Lesser Beastslayer"] = "Lesser Beastslayer"
MSC.L["Minor Beastslayer"] = "Minor Beastslayer"
MSC.L["Adamantite Scope"] = "Adamantite Scope"
MSC.L["Khorium Scope"] = "Khorium Scope"
MSC.L["Stabilized Eternium Scope"] = "Stabilized Eternium Scope"
MSC.L["Sniper Scope"] = "Sniper Scope"
MSC.L["Accurate Scope"] = "Accurate Scope"
MSC.L["Standard Scope"] = "Standard Scope"
MSC.L["Biznicks Accurascope"] = "Biznicks Accurascope"
MSC.L["Major Stamina"] = "Major Stamina"
MSC.L["Intellect"] = "Intellect"
MSC.L["Shield Block"] = "Shield Block"
MSC.L["Lesser Stamina"] = "Lesser Stamina"
MSC.L["Greater Spirit"] = "Greater Spirit"
MSC.L["Greater Stamina"] = "Greater Stamina"
MSC.L["Felsteel Shield Spike"] = "Felsteel Shield Spike"
MSC.L["Thorium Shield Spike"] = "Thorium Shield Spike"
MSC.L["Mithril Shield Spike"] = "Mithril Shield Spike"
MSC.L["Iron Shield Spike"] = "Iron Shield Spike"
MSC.L["Glyph of Power"] = "Glyph of Power"
MSC.L["Glyph of Ferocity"] = "Glyph of Ferocity"
MSC.L["Glyph of the Defender"] = "Glyph of the Defender"
MSC.L["Glyph of Renewal"] = "Glyph of Renewal"
MSC.L["Glyph of the Gladiator"] = "Glyph of the Gladiator"
MSC.L["Glyph of the Outcast"] = "Glyph of the Outcast"
MSC.L["Lesser Arcanum (Agi)"] = "Lesser Arcanum (Agi)"
MSC.L["Lesser Arcanum (Int)"] = "Lesser Arcanum (Int)"
MSC.L["Lesser Arcanum (Str)"] = "Lesser Arcanum (Str)"
MSC.L["Syncretist's Sigil"] = "Syncretist's Sigil"
MSC.L["Greater Inscription of the Orb"] = "Greater Inscription of the Orb"
MSC.L["Greater Inscription of Vengeance"] = "Greater Inscription of Vengeance"
MSC.L["Greater Inscription of the Knight"] = "Greater Inscription of the Knight"
MSC.L["Greater Inscription of the Oracle"] = "Greater Inscription of the Oracle"
MSC.L["Inscription of the Orb"] = "Inscription of the Orb"
MSC.L["Inscription of Vengeance"] = "Inscription of Vengeance"
MSC.L["Inscription of the Knight"] = "Inscription of the Knight"
MSC.L["Inscription of the Oracle"] = "Inscription of the Oracle"
MSC.L["Zandalar Signet of Mojo"] = "Zandalar Signet of Mojo"
MSC.L["Zandalar Signet of Might"] = "Zandalar Signet of Might"
MSC.L["Zandalar Signet of Serenity"] = "Zandalar Signet of Serenity"
MSC.L["Greater Agility (+12)"] = "Greater Agility (+12)"
MSC.L["Spell Penetration"] = "Spell Penetration"
MSC.L["Steelweave"] = "Steelweave"
MSC.L["Major Armor"] = "Major Armor"
MSC.L["Lesser Agility (+3)"] = "Lesser Agility (+3)"
MSC.L["Greater Resistance"] = "Greater Resistance"
MSC.L["Superior Defense (+70)"] = "Superior Defense (+70)"
MSC.L["Greater Defense (+50)"] = "Greater Defense (+50)"
MSC.L["Minor Agility (+1)"] = "Minor Agility (+1)"
MSC.L["Subtlety (-2% Threat]"] = "Subtlety (-2% Threat]"
MSC.L["Dodge (+1%)"] = "Dodge (+1%)"
MSC.L["Major Resistance (+7)"] = "Major Resistance (+7)"
MSC.L["Greater Shadow Resistance"] = "Greater Shadow Resistance"
MSC.L["Subtlety"] = "Subtlety"
MSC.L["Exceptional Stats (+6)"] = "Exceptional Stats (+6)"
MSC.L["Major Health (+150)"] = "Major Health (+150)"
MSC.L["Major Resilience"] = "Major Resilience"
MSC.L["Restore Mana Prime"] = "Restore Mana Prime"
MSC.L["Greater Stats (+4)"] = "Greater Stats (+4)"
MSC.L["Minor Stats (+1)"] = "Minor Stats (+1)"
MSC.L["Major Health (+100)"] = "Major Health (+100)"
MSC.L["Stats (+3)"] = "Stats (+3)"
MSC.L["Lesser Stats (+2)"] = "Lesser Stats (+2)"
MSC.L["Major Mana (+100)"] = "Major Mana (+100)"
MSC.L["Superior Health (+50)"] = "Superior Health (+50)"
MSC.L["Minor Health (+5)"] = "Minor Health (+5)"
MSC.L["Lesser Health (+15)"] = "Lesser Health (+15)"
MSC.L["Health (+25)"] = "Health (+25)"
MSC.L["Greater Health (+35)"] = "Greater Health (+35)"
MSC.L["Mana (+50)"] = "Mana (+50)"
MSC.L["Lesser Mana (+30)"] = "Lesser Mana (+30)"
MSC.L["Brawn (+12 Str)"] = "Brawn (+12 Str)"
MSC.L["Spellpower (+15)"] = "Spellpower (+15)"
MSC.L["Major Healing (+30)"] = "Major Healing (+30)"
MSC.L["Assault (+24 AP)"] = "Assault (+24 AP)"
MSC.L["Major Defense"] = "Major Defense"
MSC.L["Fortitude (+12 Stam)"] = "Fortitude (+12 Stam)"
MSC.L["Intellect +7"] = "Intellect +7"
MSC.L["Spirit +9"] = "Spirit +9"
MSC.L["Minor Strength (+1)"] = "Minor Strength (+1)"
MSC.L["Superior Strength (+9)"] = "Superior Strength (+9)"
MSC.L["Superior Stamina (+9)"] = "Superior Stamina (+9)"
MSC.L["Mana Regen (+4mp5)"] = "Mana Regen (+4mp5)"
MSC.L["Healing Power (+24)"] = "Healing Power (+24)"
MSC.L["Major Strength (+12)"] = "Major Strength (+12)"
MSC.L["Major Intellect (+12)"] = "Major Intellect (+12)"
MSC.L["Minor Spirit (+1)"] = "Minor Spirit (+1)"
MSC.L["Lesser Spirit (+3)"] = "Lesser Spirit (+3)"
MSC.L["Spirit (+5)"] = "Spirit (+5)"
MSC.L["Greater Spirit (+7)"] = "Greater Spirit (+7)"
MSC.L["Minor Stamina (+1)"] = "Minor Stamina (+1)"
MSC.L["Lesser Stamina (+3)"] = "Lesser Stamina (+3)"
MSC.L["Stamina (+5)"] = "Stamina (+5)"
MSC.L["Greater Stamina (+7)"] = "Greater Stamina (+7)"
MSC.L["Superior Agility (+15)"] = "Superior Agility (+15)"
MSC.L["Major Spellpower (+20)"] = "Major Spellpower (+20)"
MSC.L["Major Healing (+35)"] = "Major Healing (+35)"
MSC.L["Assault (+26 AP)"] = "Assault (+26 AP)"
MSC.L["Threat (+Hit)"] = "Threat (+Hit)"
MSC.L["Blast (+Crit)"] = "Blast (+Crit)"
MSC.L["Agility +7"] = "Agility +7"
MSC.L["Greater Strength (+7)"] = "Greater Strength (+7)"
MSC.L["Greater Agility (Classic +7)"] = "Greater Agility (Classic +7)"
MSC.L["Agility (+5)"] = "Agility (+5)"
MSC.L["Riding Skill"] = "Riding Skill"
MSC.L["Strength (+5)"] = "Strength (+5)"
MSC.L["Shadow Power (+20)"] = "Shadow Power (+20)"
MSC.L["Frost Power (+20)"] = "Frost Power (+20)"
MSC.L["Fire Power (+20)"] = "Fire Power (+20)"
MSC.L["Healing Power (+30)"] = "Healing Power (+30)"
MSC.L["Precision (+15 Hit)"] = "Precision (+15 Hit)"
MSC.L["Spell Strike (+15 Hit)"] = "Spell Strike (+15 Hit)"
MSC.L["Glove Reinforcements"] = "Glove Reinforcements"
MSC.L["Runic Spellthread"] = "Runic Spellthread"
MSC.L["Golden Spellthread"] = "Golden Spellthread"
MSC.L["Nethercobra Leg Armor"] = "Nethercobra Leg Armor"
MSC.L["Nethercleft Leg Armor"] = "Nethercleft Leg Armor"
MSC.L["Cobrahide Leg Armor"] = "Cobrahide Leg Armor"
MSC.L["Mystic Spellthread"] = "Mystic Spellthread"
MSC.L["Clefthide Leg Armor"] = "Clefthide Leg Armor"
MSC.L["Lesser Arcanum of Rumination"] = "Lesser Arcanum of Rumination"
MSC.L["Lesser Arcanum of Constitution"] = "Lesser Arcanum of Constitution"
MSC.L["Boar's Speed"] = "Boar's Speed"
MSC.L["Cat's Swiftness"] = "Cat's Swiftness"
MSC.L["Surefooted"] = "Surefooted"
MSC.L["Minor Agility (+1)"] = "Minor Agility (+1)"
MSC.L["Minor Speed"] = "Minor Speed"
MSC.L["Spirit (+5)"] = "Spirit (+5)"
MSC.L["Lesser Spirit (+3)"] = "Lesser Spirit (+3)"
MSC.L["Minor Spirit (+1)"] = "Minor Spirit (+1)"
MSC.L["Greater Stamina (+7)"] = "Greater Stamina (+7)"
MSC.L["Stamina (+5)"] = "Stamina (+5)"
MSC.L["Lesser Stamina (+3)"] = "Lesser Stamina (+3)"
MSC.L["Minor Stamina (+1)"] = "Minor Stamina (+1)"
MSC.L["Agility (+5)"] = "Agility (+5)"
MSC.L["Lesser Agility (+3)"] = "Lesser Agility (+3)"
MSC.L["Fortitude (+12 Stam)"] = "Fortitude (+12 Stam)"
MSC.L["Dexterity (+12 Agi)"] = "Dexterity (+12 Agi)"
MSC.L["Surefooted (+5% Resist)"] = "Surefooted (+5% Resist)"
MSC.L["Spellpower"] = "Spellpower"
MSC.L["Healing Power"] = "Healing Power"
MSC.L["Stats"] = "Stats"
MSC.L["Striking"] = "Striking"
MSC.L["Minor Haste"] = "Minor Haste"
MSC.L["Winter's Might (+7 SP)"] = "Winter's Might (+7 SP)"
MSC.L["Lesser Intellect (+6)"] = "Lesser Intellect (+6)"
MSC.L["Major Intellect (+22)"] = "Major Intellect (+22)"
MSC.L["Major Spirit (+20)"] = "Major Spirit (+20)"
MSC.L["Impact (+5 Dmg)"] = "Impact (+5 Dmg)"
MSC.L["Lesser Absorption"] = "Lesser Absorption"
MSC.L["Power of the Scourge"] = "Power of the Scourge"
MSC.L["Fortitude of the Scourge"] = "Fortitude of the Scourge"
MSC.L["Might of the Scourge"] = "Might of the Scourge"
MSC.L["Resilience of the Scourge"] = "Resilience of the Scourge"

-- 4. GEMS
MSC.L["Void Sphere"] = "Void Sphere"
MSC.L["Bold Living Ruby"] = "Bold Living Ruby"
MSC.L["Delicate Living Ruby"] = "Delicate Living Ruby"
MSC.L["Runed Living Ruby"] = "Runed Living Ruby"
MSC.L["Bright Living Ruby"] = "Bright Living Ruby"
MSC.L["Subtle Living Ruby"] = "Subtle Living Ruby"
MSC.L["Flashing Living Ruby"] = "Flashing Living Ruby"
MSC.L["Teardrop Living Ruby"] = "Teardrop Living Ruby"
MSC.L["Runed Ornate Ruby"] = "Runed Ornate Ruby"
MSC.L["Bold Ornate Ruby"] = "Bold Ornate Ruby"
MSC.L["Solid Star of Elune"] = "Solid Star of Elune"
MSC.L["Sparkling Star of Elune"] = "Sparkling Star of Elune"
MSC.L["Lustrous Star of Elune"] = "Lustrous Star of Elune"
MSC.L["Stormy Star of Elune"] = "Stormy Star of Elune"
MSC.L["Eye of the Sea"] = "Eye of the Sea"
MSC.L["Rigid Dawnstone"] = "Rigid Dawnstone"
MSC.L["Smooth Dawnstone"] = "Smooth Dawnstone"
MSC.L["Brilliant Dawnstone"] = "Brilliant Dawnstone"
MSC.L["Thick Dawnstone"] = "Thick Dawnstone"
MSC.L["Mystic Dawnstone"] = "Mystic Dawnstone"
MSC.L["Gleaming Dawnstone"] = "Gleaming Dawnstone"
MSC.L["Great Dawnstone"] = "Great Dawnstone"
MSC.L["Smooth Ornate Dawnstone"] = "Smooth Ornate Dawnstone"
MSC.L["Inscribed Noble Topaz"] = "Inscribed Noble Topaz"
MSC.L["Etched Noble Topaz"] = "Etched Noble Topaz"
MSC.L["Potent Noble Topaz"] = "Potent Noble Topaz"
MSC.L["Veiled Noble Topaz"] = "Veiled Noble Topaz"
MSC.L["Glinting Noble Topaz"] = "Glinting Noble Topaz"
MSC.L["Luminous Noble Topaz"] = "Luminous Noble Topaz"
MSC.L["Inscribed Ornate Topaz"] = "Inscribed Ornate Topaz"
MSC.L["Sovereign Nightseye"] = "Sovereign Nightseye"
MSC.L["Shifting Nightseye"] = "Shifting Nightseye"
MSC.L["Glowing Nightseye"] = "Glowing Nightseye"
MSC.L["Purified Nightseye"] = "Purified Nightseye"
MSC.L["Royal Nightseye"] = "Royal Nightseye"
MSC.L["Balanced Nightseye"] = "Balanced Nightseye"
MSC.L["Purified Shadow Pearl"] = "Purified Shadow Pearl"
MSC.L["Regal Nightseye"] = "Regal Nightseye"
MSC.L["Enduring Talasite"] = "Enduring Talasite"
MSC.L["Dazzling Talasite"] = "Dazzling Talasite"
MSC.L["Jagged Talasite"] = "Jagged Talasite"
MSC.L["Vivid Talasite"] = "Vivid Talasite"
MSC.L["Steady Talasite"] = "Steady Talasite"
MSC.L["Relentless Earthstorm"] = "Relentless Earthstorm"
MSC.L["Chaotic Skyfire"] = "Chaotic Skyfire"
MSC.L["Mystical Skyfire"] = "Mystical Skyfire"
MSC.L["Powerful Earthstorm"] = "Powerful Earthstorm"
MSC.L["Brutal Earthstorm"] = "Brutal Earthstorm"
MSC.L["Insightful Earthstorm"] = "Insightful Earthstorm"
MSC.L["Destructive Skyfire"] = "Destructive Skyfire"
MSC.L["Swift Starfire"] = "Swift Starfire"
MSC.L["Bracing Earthstorm"] = "Bracing Earthstorm"
MSC.L["Bold Crimson Spinel"] = "Bold Crimson Spinel"
MSC.L["Delicate Crimson Spinel"] = "Delicate Crimson Spinel"
MSC.L["Runed Crimson Spinel"] = "Runed Crimson Spinel"
MSC.L["Teardrop Crimson Spinel"] = "Teardrop Crimson Spinel"
MSC.L["Solid Empyrean Sapphire"] = "Solid Empyrean Sapphire"
MSC.L["Sparkling Empyrean Sapphire"] = "Sparkling Empyrean Sapphire"
MSC.L["Stormy Empyrean Sapphire"] = "Stormy Empyrean Sapphire"
MSC.L["Brilliant Lionseye"] = "Brilliant Lionseye"
MSC.L["Smooth Lionseye"] = "Smooth Lionseye"
MSC.L["Rigid Lionseye"] = "Rigid Lionseye"
MSC.L["Thick Lionseye"] = "Thick Lionseye"
MSC.L["Mystic Lionseye"] = "Mystic Lionseye"
MSC.L["Great Lionseye"] = "Great Lionseye"
MSC.L["Inscribed Pyrestone"] = "Inscribed Pyrestone"
MSC.L["Potent Pyrestone"] = "Potent Pyrestone"
MSC.L["Luminous Pyrestone"] = "Luminous Pyrestone"
MSC.L["Glinting Pyrestone"] = "Glinting Pyrestone"
MSC.L["Veiled Pyrestone"] = "Veiled Pyrestone"
MSC.L["Wicked Pyrestone"] = "Wicked Pyrestone"
MSC.L["Sovereign Shadowsong Amethyst"] = "Sovereign Shadowsong Amethyst"
MSC.L["Shifting Shadowsong Amethyst"] = "Shifting Shadowsong Amethyst"
MSC.L["Glowing Shadowsong Amethyst"] = "Glowing Shadowsong Amethyst"
MSC.L["Royal Shadowsong Amethyst"] = "Royal Shadowsong Amethyst"
MSC.L["Purified Shadowsong Amethyst"] = "Purified Shadowsong Amethyst"
MSC.L["Enduring Seaspray Emerald"] = "Enduring Seaspray Emerald"
MSC.L["Jagged Seaspray Emerald"] = "Jagged Seaspray Emerald"
MSC.L["Crimson Sun"] = "Crimson Sun"
MSC.L["Don Julio's Heart"] = "Don Julio's Heart"
MSC.L["Kailee's Rose"] = "Kailee's Rose"
MSC.L["Don Amancio's Heart"] = "Don Amancio's Heart"
MSC.L["Delicate Fire Ruby"] = "Delicate Fire Ruby"
MSC.L["Falling Star"] = "Falling Star"
MSC.L["Sparkling Falling Star"] = "Sparkling Falling Star"
MSC.L["Lustrous Falling Star"] = "Lustrous Falling Star"
MSC.L["Stormy Falling Star"] = "Stormy Falling Star"
MSC.L["Blood of Amber"] = "Blood of Amber"
MSC.L["Stone of Blades"] = "Stone of Blades"
MSC.L["Brilliant Bladestone"] = "Brilliant Bladestone"
MSC.L["Great Bladestone"] = "Great Bladestone"
MSC.L["Rigid Bladestone"] = "Rigid Bladestone"
MSC.L["Mystic Bladestone"] = "Mystic Bladestone"
MSC.L["Facet of Eternity"] = "Facet of Eternity"
MSC.L["Quick Lionseye"] = "Quick Lionseye"
MSC.L["Reckless Pyrestone"] = "Reckless Pyrestone"
MSC.L["Luminous Fire Opal"] = "Luminous Fire Opal"
MSC.L["Glinting Fire Opal"] = "Glinting Fire Opal"
MSC.L["Etched Fire Opal"] = "Etched Fire Opal"
MSC.L["Shining Fire Opal"] = "Shining Fire Opal"
MSC.L["Deadly Fire Opal"] = "Deadly Fire Opal"
MSC.L["Potent Fire Opal"] = "Potent Fire Opal"
MSC.L["Iridescent Fire Opal"] = "Iridescent Fire Opal"
MSC.L["Resplendent Fire Opal"] = "Resplendent Fire Opal"
MSC.L["Sovereign Tanzanite"] = "Sovereign Tanzanite"
MSC.L["Shifting Tanzanite"] = "Shifting Tanzanite"
MSC.L["Glowing Tanzanite"] = "Glowing Tanzanite"
MSC.L["Brutal Tanzanite"] = "Brutal Tanzanite"
MSC.L["Fluorescent Tanzanite"] = "Fluorescent Tanzanite"
MSC.L["Royal Tanzanite"] = "Royal Tanzanite"
MSC.L["Steady Seaspray Emerald"] = "Steady Seaspray Emerald"
MSC.L["Forceful Seaspray Emerald"] = "Forceful Seaspray Emerald"
MSC.L["Sundered Chrysoprase"] = "Sundered Chrysoprase"
MSC.L["Jagged Chrysoprase"] = "Jagged Chrysoprase"
MSC.L["Vivid Chrysoprase"] = "Vivid Chrysoprase"
MSC.L["Lambent Chrysoprase"] = "Lambent Chrysoprase"
MSC.L["Eternal Earthstorm"] = "Eternal Earthstorm"
MSC.L["Bold Blood Garnet"] = "Bold Blood Garnet"
MSC.L["Delicate Blood Garnet"] = "Delicate Blood Garnet"
MSC.L["Runed Blood Garnet"] = "Runed Blood Garnet"
MSC.L["Bright Blood Garnet"] = "Bright Blood Garnet"
MSC.L["Teardrop Blood Garnet"] = "Teardrop Blood Garnet"
MSC.L["Solid Azure Moonstone"] = "Solid Azure Moonstone"
MSC.L["Sparkling Azure Moonstone"] = "Sparkling Azure Moonstone"
MSC.L["Lustrous Azure Moonstone"] = "Lustrous Azure Moonstone"
MSC.L["Stormy Azure Moonstone"] = "Stormy Azure Moonstone"
MSC.L["Rigid Golden Draenite"] = "Rigid Golden Draenite"
MSC.L["Smooth Golden Draenite"] = "Smooth Golden Draenite"
MSC.L["Brilliant Golden Draenite"] = "Brilliant Golden Draenite"
MSC.L["Thick Golden Draenite"] = "Thick Golden Draenite"
MSC.L["Gleaming Golden Draenite"] = "Gleaming Golden Draenite"
MSC.L["Inscribed Flame Spessarite"] = "Inscribed Flame Spessarite"
MSC.L["Glinting Flame Spessarite"] = "Glinting Flame Spessarite"
MSC.L["Potent Flame Spessarite"] = "Potent Flame Spessarite"
MSC.L["Veiled Flame Spessarite"] = "Veiled Flame Spessarite"
MSC.L["Luminous Flame Spessarite"] = "Luminous Flame Spessarite"
MSC.L["Sovereign Shadow Draenite"] = "Sovereign Shadow Draenite"
MSC.L["Shifting Shadow Draenite"] = "Shifting Shadow Draenite"
MSC.L["Glowing Shadow Draenite"] = "Glowing Shadow Draenite"
MSC.L["Royal Shadow Draenite"] = "Royal Shadow Draenite"
MSC.L["Enduring Deep Peridot"] = "Enduring Deep Peridot"
MSC.L["Dazzling Deep Peridot"] = "Dazzling Deep Peridot"
MSC.L["Jagged Deep Peridot"] = "Jagged Deep Peridot"
MSC.L["Radiant Deep Peridot"] = "Radiant Deep Peridot"

-- 5. TRINKET NOTES & PROCS
MSC.L["Use: Teleport (8 possible malfunctions!)"] = "Use: Teleport (8 possible malfunctions!)"
MSC.L["Proc: 170 SP (On Resist Only)"] = "Proc: 170 SP (On Resist Only)"
MSC.L["Passive: 15 mp5 + Heal Battery"] = "Passive: 15 mp5 + Heal Battery"
MSC.L["Pet Proc"] = "Pet Proc"
MSC.L["Passive: Resistances not valued"] = "Passive: Resistances not valued"
MSC.L["Use: 50% Haste - Burst Value"] = "Use: 50% Haste - Burst Value"
MSC.L["Powershift: Energy Refund valued as 80 AP"] = "Powershift: Energy Refund valued as 80 AP"
MSC.L["Use: 500 Avg Heal (30m CD)"] = "Use: 500 Avg Heal (30m CD)"
MSC.L["Use: 1.67 Avg mp5 (15m CD)"] = "Use: 1.67 Avg mp5 (15m CD)"
MSC.L["Use: ~2.8 Avg mp5 from cost reduction (15m CD)"] = "Use: ~2.8 Avg mp5 from cost reduction (15m CD)"
MSC.L["Use: ~1.4 Avg hp5 (30m CD)"] = "Use: ~1.4 Avg hp5 (30m CD)"
MSC.L["Use: 12 Avg mp5 (5m CD)"] = "Use: 12 Avg mp5 (5m CD)"
MSC.L["Use: 6 Avg mp5 (3m CD)"] = "Use: 6 Avg mp5 (3m CD)"
MSC.L["Use: ~18.3 Avg mp5 from cost reduction (1m CD)"] = "Use: ~18.3 Avg mp5 from cost reduction (1m CD)"
MSC.L["Equip: Imp Firebolt Dmg +8.1 (10 SP Proxy)"] = "Equip: Imp Firebolt Dmg +8.1 (10 SP Proxy)"
MSC.L["Equip: Pet Dmg +4% (20 AP Proxy)"] = "Equip: Pet Dmg +4% (20 AP Proxy)"
MSC.L["Equip: 13 Fire Thorns (15 SP Proxy)"] = "Equip: 13 Fire Thorns (15 SP Proxy)"
MSC.L["Equip: Reduced Fall Dmg (1 Agi Proxy)"] = "Equip: Reduced Fall Dmg (1 Agi Proxy)"
MSC.L["Use: 1200 Dmg (2m CD / ~140 AP Proxy)"] = "Use: 1200 Dmg (2m CD / ~140 AP Proxy)"
MSC.L["Use: 450 AoE Dmg (10m CD / ~10.5 AP Proxy)"] = "Use: 450 AoE Dmg (10m CD / ~10.5 AP Proxy)"
MSC.L["Use: 30% Speed + Snare Immune (5 Agi Proxy)"] = "Use: 30% Speed + Snare Immune (5 Agi Proxy)"
MSC.L["Use: 4.5 Avg AP (5m CD)"] = "Use: 4.5 Avg AP (5m CD)"
MSC.L["Use: 1.33 Avg DR (5m CD / Block Proxy)"] = "Use: 1.33 Avg DR (5m CD / Block Proxy)"
MSC.L["Use: Summon Truesilver Boar (14 AP Proxy)"] = "Use: Summon Truesilver Boar (14 AP Proxy)"
MSC.L["Use: 2.33 Avg DR (5m CD / Block Proxy)"] = "Use: 2.33 Avg DR (5m CD / Block Proxy)"
MSC.L["Use: 25 Avg Haste (2m CD)"] = "Use: 25 Avg Haste (2m CD)"
MSC.L["Use: Threat Reduction (5 Agi Proxy)"] = "Use: Threat Reduction (5 Agi Proxy)"
MSC.L["Use: 39.2 Avg Block Value (2m CD)"] = "Use: 39.2 Avg Block Value (2m CD)"
MSC.L["Equip: Fire Dmg Proc (~35 AP Proxy)"] = "Equip: Fire Dmg Proc (~35 AP Proxy)"
MSC.L["Equip: 150 AP (vs Undead/Demons)"] = "Equip: 150 AP (vs Undead/Demons)"
MSC.L["Equip: 85 SP (vs Undead/Demons)"] = "Equip: 85 SP (vs Undead/Demons)"
MSC.L["Use: 43.3 Avg AP (2m CD)"] = "Use: 43.3 Avg AP (2m CD)"
MSC.L["Use: 21.7 Avg SP (2m CD)"] = "Use: 21.7 Avg SP (2m CD)"
MSC.L["Use: Summon Felsteel Boar (20 AP Proxy)"] = "Use: Summon Felsteel Boar (20 AP Proxy)"
MSC.L["Use: 21.7 Avg Haste (2m CD)"] = "Use: 21.7 Avg Haste (2m CD)"
MSC.L["Use: 46.3 Avg AP (2m CD)"] = "Use: 46.3 Avg AP (2m CD)"
MSC.L["Use: 33.3 Avg AP (2m CD)"] = "Use: 33.3 Avg AP (2m CD)"
MSC.L["Use: 39.7 Avg Heal / 13.2 Avg SP (90s CD)"] = "Use: 39.7 Avg Heal / 13.2 Avg SP (90s CD)"
MSC.L["Use: 50 Avg Spirit (2m CD)"] = "Use: 50 Avg Spirit (2m CD)"
MSC.L["Use: 5 Spell Charges (37.5 Avg Heal Proxy / 2m CD)"] = "Use: 5 Spell Charges (37.5 Avg Heal Proxy / 2m CD)"
MSC.L["Use: 17.3 Avg SP (2m CD)"] = "Use: 17.3 Avg SP (2m CD)"
MSC.L["Use: 23.1 Avg AP (2m CD)"] = "Use: 23.1 Avg AP (2m CD)"
MSC.L["Use: 35.5 Avg Heal / 11.8 Avg SP (2m CD)"] = "Use: 35.5 Avg Heal / 11.8 Avg SP (2m CD)"
MSC.L["Use: 47 Avg Heal / 15.6 Avg SP (2m CD)"] = "Use: 47 Avg Heal / 15.6 Avg SP (2m CD)"
MSC.L["Use: 37.5 Max mp5 (Requires Killingblow / 2m CD)"] = "Use: 37.5 Max mp5 (Requires Killingblow / 2m CD)"
MSC.L["Use: 37.5 Max hp5 (Requires Killingblow / 2m CD)"] = "Use: 37.5 Max hp5 (Requires Killingblow / 2m CD)"
MSC.L["Equip: 100 Max mp5 (Requires Killingblows / 10s CD)"] = "Equip: 100 Max mp5 (Requires Killingblows / 10s CD)"
MSC.L["Equip: 100 Max hp5 (Requires Killingblows / 10s CD)"] = "Equip: 100 Max hp5 (Requires Killingblows / 10s CD)"
MSC.L["Equip: Melee Heal or Ranged Mana Proc (~10 mp5 Proxy)"] = "Equip: Melee Heal or Ranged Mana Proc (~10 mp5 Proxy)"
MSC.L["Use: Stacking Heal Bonus (~30 Heal Proxy)"] = "Use: Stacking Heal Bonus (~30 Heal Proxy)"
MSC.L["Equip: +70 AP to Battle Shout"] = "Equip: +70 AP to Battle Shout"
MSC.L["Equip: Shot Dmg Bonus (~40 RAP Proxy)"] = "Equip: Shot Dmg Bonus (~40 RAP Proxy)"
MSC.L["Equip: Threat Reduction on Crits (5 Agi Proxy)"] = "Equip: Threat Reduction on Crits (5 Agi Proxy)"
MSC.L["Equip: 28.1 Avg SP / ~25 mp5 via Mana Gems"] = "Equip: 28.1 Avg SP / ~25 mp5 via Mana Gems"
MSC.L["Use: 29.2 Avg Haste (2m CD)"] = "Use: 29.2 Avg Haste (2m CD)"
MSC.L["Use: 36 Avg AP (1m CD)"] = "Use: 36 Avg AP (1m CD)"
MSC.L["Use: 66 Avg Heal / 22 Avg SP (2m CD)"] = "Use: 66 Avg Heal / 22 Avg SP (2m CD)"
MSC.L["Use: 35.2 Avg SP (2m CD)"] = "Use: 35.2 Avg SP (2m CD)"
MSC.L["Use: 60 Avg AP (2m CD)"] = "Use: 60 Avg AP (2m CD)"
MSC.L["Use: 33.3 Avg mp5 (5m CD)"] = "Use: 33.3 Avg mp5 (5m CD)"
MSC.L["Use: 145.8 Avg Health (3m CD)"] = "Use: 145.8 Avg Health (3m CD)"
MSC.L["Use: Summon Khorium Boar (20 AP Proxy)"] = "Use: Summon Khorium Boar (20 AP Proxy)"
MSC.L["Use: 53.3 Avg AP (90s CD)"] = "Use: 53.3 Avg AP (90s CD)"
MSC.L["Use: 25 Avg mp5 (3m CD)"] = "Use: 25 Avg mp5 (3m CD)"
MSC.L["Use: 49.5 Avg Heal / 16.5 Avg SP (2m CD)"] = "Use: 49.5 Avg Heal / 16.5 Avg SP (2m CD)"
MSC.L["Use: 33.3 Avg Block Value (2m CD)"] = "Use: 33.3 Avg Block Value (2m CD)"
MSC.L["Use: 25.8 Avg SP (2m CD)"] = "Use: 25.8 Avg SP (2m CD)"
MSC.L["Use: 3.3 Avg hp5 (10m CD)"] = "Use: 3.3 Avg hp5 (10m CD)"
MSC.L["CC Break (Rank 1)"] = "CC Break (Rank 1)"
MSC.L["CC Break (Rank 2)"] = "CC Break (Rank 2)"
MSC.L["CC Break (Rank 3)"] = "CC Break (Rank 3)"

-- =============================================================
-- Data_sets
-- =============================================================

-- 1. CLASSIC ERA PROC & TRINKET DESCRIPTIONS
MSC.L["Classic Caster BiS"] = "Classic Caster BiS"
MSC.L["Classic Physical BiS"] = "Classic Physical BiS"
MSC.L["Legendary Threat Generation"] = "Legendary Threat Generation"
MSC.L["Classic Top Tier (Prot Pally)"] = "Classic Top Tier (Prot Pally)"
MSC.L["Chance to Trigger Bladestorm"] = "Chance to Trigger Bladestorm"
MSC.L["Armor Penetration Proc"] = "Armor Penetration Proc"
MSC.L["Haste Use Effect"] = "Haste Use Effect"
MSC.L["Attack Power Use Effect"] = "Attack Power Use Effect"
MSC.L["Ramping Attack Power"] = "Ramping Attack Power"
MSC.L["Haste Use Effect (Mage Only)"] = "Haste Use Effect (Mage Only)"
MSC.L["Heals Grant Shield"] = "Heals Grant Shield"
MSC.L["Healing/Damage Charge System"] = "Healing/Damage Charge System"
MSC.L["Spell Power Use Effect"] = "Spell Power Use Effect"
MSC.L["Health Use Effect"] = "Health Use Effect"
MSC.L["Decreasing Spell Power/Damage"] = "Decreasing Spell Power/Damage"
MSC.L["High Regen Scaling (Warrior)"] = "High Regen Scaling (Warrior)"
MSC.L["Summons Battle Chicken (Haste Buff)"] = "Summons Battle Chicken (Haste Buff)"
MSC.L["Summons Dragonling (Fire Vuln.)"] = "Summons Dragonling (Fire Vuln.)"
MSC.L["Burst Damage (Life Cost)"] = "Burst Damage (Life Cost)"
MSC.L["Run Speed Use Effect"] = "Run Speed Use Effect"
MSC.L["Ranged Damage/Stun/Daze"] = "Ranged Damage/Stun/Daze"

-- 2. TBC PROC & TRINKET DESCRIPTIONS
MSC.L["Chance on hit: 2 Extra Attacks"] = "Chance on hit: 2 Extra Attacks"
MSC.L["Chance on hit: 1 Extra Attack (2s CD)"] = "Chance on hit: 1 Extra Attack (2s CD)"
MSC.L["Chance on hit: 60 Avg Fire Dmg"] = "Chance on hit: 60 Avg Fire Dmg"
MSC.L["Equip: 250 Nature Dmg Proc"] = "Equip: 250 Nature Dmg Proc"
MSC.L["Equip: 277 Nature Poison Dmg Proc"] = "Equip: 277 Nature Poison Dmg Proc"
MSC.L["Equip: 380 Avg Dmg on DoT tick (15s CD)"] = "Equip: 380 Avg Dmg on DoT tick (15s CD)"
MSC.L["Equip: 750 Avg Dmg every 3 Crits (2.5s CD)"] = "Equip: 750 Avg Dmg every 3 Crits (2.5s CD)"
MSC.L["Equip: 2% Chance on Struck for Holy Shield"] = "Equip: 2% Chance on Struck for Holy Shield"
MSC.L["Equip: 1% Chance on Struck for -25 Dmg Taken"] = "Equip: 1% Chance on Struck for -25 Dmg Taken"
MSC.L["Equip: 1% Chance on Struck for 250 Party Armor"] = "Equip: 1% Chance on Struck for 250 Party Armor"
MSC.L["Equip: 2% Chance on Struck for +25 All Stats"] = "Equip: 2% Chance on Struck for +25 All Stats"
MSC.L["Equip: 152 Dodge at <35% HP (30s CD)"] = "Equip: 152 Dodge at <35% HP (30s CD)"
MSC.L["Equip: 2% Chance on Struck for 350 Armor"] = "Equip: 2% Chance on Struck for 350 Armor"
MSC.L["Equip: 150 Avg Heal on melee"] = "Equip: 150 Avg Heal on melee"
MSC.L["Equip: 100% Mana Regen while casting (15s)"] = "Equip: 100% Mana Regen while casting (15s)"
MSC.L["Chance to Self-Resurrect"] = "Chance to Self-Resurrect"
MSC.L["Equip: 260 Mana on Struck"] = "Equip: 260 Mana on Struck"
MSC.L["Equip: 150 Avg Mana (17s CD)"] = "Equip: 150 Avg Mana (17s CD)"
MSC.L["Equip: 150 Avg Mana (25s CD)"] = "Equip: 150 Avg Mana (25s CD)"
MSC.L["Equip: 2% Chance on Heal for Free Cast (450 Mana)"] = "Equip: 2% Chance on Heal for Free Cast (450 Mana)"
MSC.L["Equip: 500 HoT (15s CD)"] = "Equip: 500 HoT (15s CD)"
MSC.L["Equip: 335 Mana (40s CD)"] = "Equip: 335 Mana (40s CD)"
MSC.L["Equip: 76 mp5 proc (50s CD)"] = "Equip: 76 mp5 proc (50s CD)"
MSC.L["Equip: 320 Haste (45s CD)"] = "Equip: 320 Haste (45s CD)"
MSC.L["Equip: Mana Regen Proc (50s CD)"] = "Equip: Mana Regen Proc (50s CD)"
MSC.L["Equip: 300 AP (50s CD)"] = "Equip: 300 AP (50s CD)"
MSC.L["Equip: 225 SP (45s CD)"] = "Equip: 225 SP (45s CD)"
MSC.L["Equip: 1000 ArP (30s CD)"] = "Equip: 1000 ArP (30s CD)"
MSC.L["Equip: 290 SP (45s CD)"] = "Equip: 290 SP (45s CD)"
MSC.L["Equip: 325 Haste (20s CD)"] = "Equip: 325 Haste (20s CD)"
MSC.L["Equip: 190 SP (45s CD)"] = "Equip: 190 SP (45s CD)"
MSC.L["Equip: 340 AP (45s CD)"] = "Equip: 340 AP (45s CD)"
MSC.L["Equip: 300 ArP (~20% Uptime)"] = "Equip: 300 ArP (~20% Uptime)"
MSC.L["Equip: Stacking AP Proc (440 Max / 45s CD)"] = "Equip: Stacking AP Proc (440 Max / 45s CD)"
MSC.L["Equip: 230 AP (45s CD)"] = "Equip: 230 AP (45s CD)"
MSC.L["Equip: 120 Max AP / 80 Max SP (Stacking)"] = "Equip: 120 Max AP / 80 Max SP (Stacking)"
MSC.L["Equip: Stacking Crit"] = "Equip: Stacking Crit"
MSC.L["Equip: 81 AP (vs Undead)"] = "Equip: 81 AP (vs Undead)"
MSC.L["Equip: Random Stat Buff on Kill"] = "Equip: Random Stat Buff on Kill"
MSC.L["Equip: 140 Max AP (Requires Killingblows)"] = "Equip: 140 Max AP (Requires Killingblows)"
MSC.L["Equip: 80 Max SP (Requires Killingblows)"] = "Equip: 80 Max SP (Requires Killingblows)"
MSC.L["Chance on hit: Haste"] = "Chance on hit: Haste"

-- 3. ASHTONGUE TALISMANS & CLASS SPECIFIC
MSC.L["Equip: Warrior Proc (Heal + 55 Str)"] = "Equip: Warrior Proc (Heal + 55 Str)"
MSC.L["Equip: Druid Proc (Str / SP / Heal)"] = "Equip: Druid Proc (Str / SP / Heal)"
MSC.L["Equip: Hunter Proc (275 AP)"] = "Equip: Hunter Proc (275 AP)"
MSC.L["Equip: Mage Proc (145 Haste)"] = "Equip: Mage Proc (145 Haste)"
MSC.L["Equip: Paladin Proc (Heal / Dmg)"] = "Equip: Paladin Proc (Heal / Dmg)"
MSC.L["Equip: Priest Proc (220 SP / Heal)"] = "Equip: Priest Proc (220 SP / Heal)"
MSC.L["Equip: Shaman Proc (Mana / 275 AP)"] = "Equip: Shaman Proc (Mana / 275 AP)"
MSC.L["Equip: Rogue Proc (145 Crit)"] = "Equip: Rogue Proc (145 Crit)"
MSC.L["Equip: Warlock Proc (220 SP)"] = "Equip: Warlock Proc (220 SP)"
MSC.L["Equip: Druid Blessing (3% Proc)"] = "Equip: Druid Blessing (3% Proc)"

-- =============================================================
-- JUDGE
-- =============================================================
L["Classic Era"] = "Classic Era"
L["TBC Edition"] = "TBC Edition"
L["|cff00ff00Sharpie's Gear Judge|r (%s) Loaded. Type /sgj for menu."] = "|cff00ff00Sharpie's Gear Judge|r (%s) Loaded. Type /sgj for menu."
L["|cffffd100SGJ Warning:|r 'Pawn' is loaded. Tooltips may look cluttered."] = "|cffffd100SGJ Warning:|r 'Pawn' is loaded. Tooltips may look cluttered."
L["|cffffd100SGJ Warning:|r 'Zygor' detected. Ensure its item scoring is disabled."] = "|cffffd100SGJ Warning:|r 'Zygor' detected. Ensure its item scoring is disabled."

-- Popups
L["|cff00ccffSharpie's Gear Judge|r\n\nProfile imported successfully!\n\nYou must reload your UI for the changes to take effect."] = "|cff00ccffSharpie's Gear Judge|r\n\nProfile imported successfully!\n\nYou must reload your UI for the changes to take effect."
L["Reload Now"] = "Reload Now"
L["Later"] = "Later"

-- Tooltip Headers
L["Judge's Score:"] = "Judge's Score:"
L["Verdict Profile:"] = "Verdict Profile:"
L["Capped"] = "Capped"
L["|cff00ffff* EQUIPPED *|r"] = "|cff00ffff* EQUIPPED *|r"
L["vs."] = "vs."
L["Judge's Note:"] = "Judge's Note:"
L["Class Bonus: "] = "Class Bonus: "

-- Upgrade/Downgrade Text
-- Note: %s is the Texture, %.1f are numbers
L["|cff00ff00%s Upgrade (+%.1f / +%.1f%%)|r"] = "|cff00ff00%s Upgrade (+%.1f / +%.1f%%)|r"
L["|cffff0000%s Downgrade (%.1f / %.1f%%)|r"] = "|cffff0000%s Downgrade (%.1f / %.1f%%)|r"
L["|cff888888= Sidegrade (0.0)|r"] = "|cff888888= Sidegrade (0.0)|r"

-- Warnings
L["|cffff0000!!! WARNING: Breaking Set Bonus (%d) !!!|r"] = "|cffff0000!!! WARNING: Breaking Set Bonus (%d) !!!|r"
L["|cff00ff00+++ GAINED: %d-pc Set Bonus! +++|r"] = "|cff00ff00+++ GAINED: %d-pc Set Bonus! +++|r"
L["  |cffff0000(Breaks %d-pc Set Bonus!)|r"] = "  |cffff0000(Breaks %d-pc Set Bonus!)|r"
L["|cff00ff00+%s (Upgrade)|r"] = "|cff00ff00+%s (Upgrade)|r"

-- Projections
L["Projected Enchant:"] = "Projected Enchant:"
L["Best Available"] = "Best Available"
L["Projected Gems:"] = "Projected Gems:"
L["+ Meta Gem Active"] = "+ Meta Gem Active"
L["- Meta Gem Inactive (Reqs unmet)"] = "- Meta Gem Inactive (Reqs unmet)"

-- Lists
L["Gains:"] = "Gains:"
L["Losses:"] = "Losses:"

-- [[ INTERFACE: VISUALS ]]
L["Tooltip Visuals"] = "Tooltip Visuals"
L["Compact Equip Text"] = "Compact Equip Text"
L["Compact Equip Tooltip"] = "Rewrites long 'Equip' sentences into concise math.\n\nExample:\n'Equip: Increases your hit rating by 20.'\nbecomes\n'Equip: +20 Hit'"
L["Shorten Stat Names"] = "Shorten Stat Names"
L["Shorten Stat Tooltip"] = "Abbreviates stat names to save space.\n\nExamples:\nStrength > Str\nAttack Power > AP"
L["Colorize Stats"] = "Colorize Stats"
L["Colorize Stats Tooltip"] = "Applies colors to stats."

-- =============================================================
-- DYNAMIC ENGINE
-- =============================================================
L["Auto: %s"] = "Auto: %s"

-- =============================================================
-- INTERFACE (Lab, Receipt, Settings)
-- =============================================================
-- Stat Logic Tooltips

L["Need %d more rating to cap."] = "Need %d more rating to cap."
L["Cap reached!"] = "Cap reached!"
L["Current Rating:"] = "Current Rating:"
L["1%% requires %.2f Rating"] = "1%% requires %.2f Rating"
L["Gear Contribution:"] = "Gear Contribution:"
L["Character Sheet:"] = "Character Sheet:"
L["%d (Includes Base/Enchants)"] = "%d (Includes Base/Enchants)"
L["Score Calculation:"] = "Score Calculation:"
L["%.2f (Weight) x %.1f (Gear)"] = "%.2f (Weight) x %.1f (Gear)"
L["Stat Weight:"] = "Stat Weight:"
L["You currently have 0 of this stat from gear."] = "You currently have 0 of this stat from gear."

-- Misc
L["Laboratory"] = "Laboratory"
L["Select..."] = "Select..."
L["(Empty)"] = "(Empty)"
L["Weapon Thunderdome"] = "Weapon Thunderdome"
L["Receipt"] = "Receipt"
L["Stat Logic"] = "Stat Logic"
L["Rating:"] = "Rating:"
L["Protocol"] = "Protocol"
L["Drag (Shift/Ctrl+Click) items to compare. 6 Sets Enter, 1 Set Wins!"] = "Drag (Shift/Ctrl+Click) items to compare. 6 Sets Enter, 1 Set Wins!"
L["Option A1: Two-Hander"] = "Option A1: Two-Hander"
L["Option B1: 1H + Shield/OH"] = "Option B1: 1H + Shield/OH"
L["Option C1: Dual Wield"] = "Option C1: Dual Wield"
L["Option A2: Two-Hander"] = "Option A2: Two-Hander"
L["Option B2: 1H + Shield/OH"] = "Option B2: 1H + Shield/OH"
L["Option C2: Dual Wield"] = "Option C2: Dual Wield"
L["Waiting for Items..."] = "Waiting for Items..."
L["Option A1 (2H)"] = "Option A1 (2H)"
L["Option B1 (1H+OH)"] = "Option B1 (1H+OH)"
L["Option C1 (DW)"] = "Option C1 (DW)"
L["Option A2 (2H)"] = "Option A2 (2H)"
L["Option B2 (1H+OH)"] = "Option B2 (1H+OH)"
L["Option C2 (DW)"] = "Option C2 (DW)"
L["%s Wins! (+%s)"] = "%s Wins! (+%s)"

-- Receipt
L["ARMOR"] = "ARMOR"
L["ACCESSORIES"] = "ACCESSORIES"
L["WEAPONS"] = "WEAPONS"
L["Head"] = "Head"
L["Shoulder"] = "Shoulder"
L["Back"] = "Back"
L["Chest"] = "Chest"
L["Wrist"] = "Wrist"
L["Hands"] = "Hands"
L["Waist"] = "Waist"
L["Legs"] = "Legs"
L["Feet"] = "Feet"
L["Neck"] = "Neck"
L["Ring 1"] = "Ring 1"
L["Ring 2"] = "Ring 2"
L["Trinket 1"] = "Trinket 1"
L["Trinket 2"] = "Trinket 2"
L["Main Hand"] = "Main Hand"
L["Off Hand"] = "Off Hand"
L["Ranged"] = "Ranged"
L["COMBINED GEAR STAT TOTALS"] = "COMBINED GEAR STAT TOTALS"
L["Score: "] = "Score: "
L["Missing Enchant!"] = "Missing Enchant!"
L["Better item in bags!"] = "Better item in bags!"

-- Settings
L["Comparison Logic"] = "Comparison Logic"
L["Enchant Mode"] = "Enchant Mode"
L["Off (Raw Stats)"] = "Off (Raw Stats)"
L["Current Only"] = "Current Only"
L["Project Best"] = "Project Best"
L["Controls how item enchantments affect the score.\n\n|cffffffffOff:|r Scores items based on base stats only.\n|cffffffffCurrent:|r Includes the value of the enchant currently on the item.\n|cffffffffProject:|r Simulates the best possible enchant for that item level."] = "Controls how item enchantments affect the score.\n\n|cffffffffOff:|r Scores items based on base stats only.\n|cffffffffCurrent:|r Includes the value of the enchant currently on the item.\n|cffffffffProject:|r Simulates the best possible enchant for that item level."

L["Gemming Logic"] = "Gemming Logic"
L["The Skeptic"] = "The Skeptic"
L["The Casual"] = "The Casual"
L["The Pro"] = "The Pro"
L["Controls how empty sockets are scored.\n\n|cffffffffSkeptic:|r Empty sockets are worth 0. Socket bonuses are ignored unless fully met.\n|cffffffffCasual:|r Assumes empty sockets are filled with Rare (Blue) quality gems.\n|cffffffffPro:|r Assumes empty sockets are filled with Epic/Best-in-Slot gems."] = "Controls how empty sockets are scored.\n\n|cffffffffSkeptic:|r Empty sockets are worth 0. Socket bonuses are ignored unless fully met.\n|cffffffffCasual:|r Assumes empty sockets are filled with Rare (Blue) quality gems.\n|cffffffffPro:|r Assumes empty sockets are filled with Epic/Best-in-Slot gems."

L["Character Profile"] = "Character Profile"
L["Auto-Detect"] = "Auto-Detect"
L["Active Scoring Profile"] = "Active Scoring Profile"
L["Manually override the scoring profile.\n\n|cffffffffAuto-Detect:|r Automatically selects a profile based on your talents and recent gameplay.\n\nSelecting a specific profile forces the addon to judge all gear for that spec, regardless of your current talents."] = "Manually override the scoring profile.\n\n|cffffffffAuto-Detect:|r Automatically selects a profile based on your talents and recent gameplay.\n\nSelecting a specific profile forces the addon to judge all gear for that spec, regardless of your current talents."

L["Interface Options"] = "Interface Options"
L["Hide Minimap Button"] = "Hide Minimap Button"
L["Hides the circular button on your minimap."] = "Hides the circular button on your minimap."
L["Hide Tooltip Verdict"] = "Hide Tooltip Verdict"
L["Stops the addon from adding scores to item tooltips."] = "Stops the addon from adding scores to item tooltips."
L["Show Only via Shift Key"] = "Show Only via Shift Key"
L["Only shows the Judge score in tooltips while holding the SHIFT key."] = "Only shows the Judge score in tooltips while holding the SHIFT key."
L["Mute Error Sounds"] = "Mute Error Sounds"
L["Stops the error sound when clicking invalid items."] = "Stops the error sound when clicking invalid items."
L["Disable Conflict Check"] = "Disable Conflict Check"
L["Stops the chat warning about Pawn/Zygor."] = "Stops the chat warning about Pawn/Zygor."

L["Secondary Spec Tracking"] = "Secondary Spec Tracking"
L["Select additional profiles to track in tooltips.\n\nIf an item is an upgrade for a checked profile, a small notification will appear at the bottom of the item tooltip."] = "Select additional profiles to track in tooltips.\n\nIf an item is an upgrade for a checked profile, a small notification will appear at the bottom of the item tooltip."

L["Import Pawn String"] = "Import Pawn String"
L["Export Data"] = "Export Data"
L["Paste Pawn string here..."] = "Paste Pawn string here..."
L["Import"] = "Import"
L["Export Data (Discord Ready)"] = "Export Data (Discord Ready)"
L["Unknown"] = "Unknown"
L["Unknown Item"] = "Unknown Item"
L["No Weights Loaded"] = "No Weights Loaded"
L["Total Score: "] = "Total Score: "
L["Scroll to Scale"] = "Scroll to Scale"
L["Hold\nto Move"] = "Hold\nto Move"

-- Stat Reasons
L["Increases Attack Power and Block Value"] = "Increases Attack Power and Block Value"
L["Increases Crit Chance, Dodge, and Armor"] = "Increases Crit Chance, Dodge, and Armor"
L["Increases total Health Pool"] = "Increases total Health Pool"
L["Increases Mana Pool and Spell Crit"] = "Increases Mana Pool and Spell Crit"
L["Increases Out-of-Combat and Spell5 Regen"] = "Increases Out-of-Combat and Spell5 Regen"
L["Increases Raw Physical Damage Output"] = "Increases Raw Physical Damage Output"
L["Reduces chance Target Parries or Dodges"] = "Reduces chance Target Parries or Dodges"
L["Ignores a portion of Target's Armor"] = "Ignores a portion of Target's Armor"
L["Reduces chance to Miss Physical attacks"] = "Reduces chance to Miss Physical attacks"
L["Increases Scaling Damage of Spells"] = "Increases Scaling Damage of Spells"
L["Increases Potency of Healing spells"] = "Increases Potency of Healing spells"
L["Reduces chance for Spells to Resist/Miss"] = "Reduces chance for Spells to Resist/Miss"
L["Constant Mana Sustain (Mp5)"] = "Constant Mana Sustain (Mp5)"
L["Chance for Extra Critical Damage/Healing"] = "Chance for Extra Critical Damage/Healing"
L["Increases Attack/Casting Speed"] = "Increases Attack/Casting Speed"
L["Reduces chance to be Crit and Hit"] = "Reduces chance to be Crit and Hit"
L["Chance to completely Avoid Physical attacks"] = "Chance to completely Avoid Physical attacks"
L["Chance to Deflect front-facing attacks"] = "Chance to Deflect front-facing attacks"
L["Increases Damage mitigated by Shield"] = "Increases Damage mitigated by Shield"
L["Chance to Mitigate damage with Shield"] = "Chance to Mitigate damage with Shield"
L["Reduces Crit Damage and Chance (PvP)"] = "Reduces Crit Damage and Chance (PvP)"
L["Reduces Incoming Physical Damage"] = "Reduces Incoming Physical Damage"

-- =============================================================
-- HELPERS & DEBUG
-- =============================================================
L["|cffff0000SGJ: Invalid Pawn string format or empty stats.|r"] = "|cffff0000SGJ: Invalid Pawn string format or empty stats.|r"
L["|cff00ff00SGJ:|r Successfully imported %s"] = "|cff00ff00SGJ:|r Successfully imported %s"

L["|cffff0000SGJ: Please hover over an item to debug.|r"] = "|cffff0000SGJ: Please hover over an item to debug.|r"
L["|cffff0000SGJ: No weights loaded.|r"] = "|cffff0000SGJ: No weights loaded.|r"
L["|cff00ccff--- SGJ DEBUG REPORT ---|r"] = "|cff00ccff--- SGJ DEBUG REPORT ---|r"
L["Item: "] = "Item: "
L["Profile: "] = "Profile: "
L["|cffffffff%s:|r %.1f x %.2f = |cff00ff00%.1f|r"] = "|cffffffff%s:|r %.1f x %.2f = |cff00ff00%.1f|r"
L["|cff888888%s: %.1f (Weight: 0)|r"] = "|cff888888%s: %.1f (Weight: 0)|r"
L["Ratio Check: "] = "Ratio Check: "
L["Useful: %.1f / Useless: %.1f"] = "Useful: %.1f / Useless: %.1f"
L["|cffff0000[FAIL] Item rejected by Bouncer (Mostly Junk)|r"] = "|cffff0000[FAIL] Item rejected by Bouncer (Mostly Junk)|r"
L["|cff00ff00[PASS] Item accepted|r"] = "|cff00ff00[PASS] Item accepted|r"
L["Final Score: "] = "Final Score: "

-- =============================================================
-- PARSER: KEYWORDS & PATTERNS
-- =============================================================
-- Classify Keywords
L["equip"] = "equip"
L["use:"] = "use:"
L["chance on"] = "chance on"
L["set:"] = "set:"
L["socket"] = "socket"
L["bonus"] = "bonus"
L["spell"] = "spell"
L["hit"] = "hit"
L["crit"] = "crit"
L["speed"] = "speed"
L["haste"] = "haste"
L["armor"] = "armor"
L["^to "] = "^to "
L["^equip: "] = "^equip: "

-- Header Patterns
L["^(.*)%s+%(?(%d+)/(%d+)%)?$"] = "^(.*)%s+%(?(%d+)/(%d+)%)?$"
L["^%s*equip:%s*"] = "^%s*equip:%s*"
L["^chance on hit: "] = "^chance on hit: "
L["^equip: chance on hit: "] = "^equip: chance on hit: "
L["^use: "] = "^use: "

-- Stat Patterns (Regex)
L["^[%+]?%s*(%d+%.?%d*)%s+(.-)[%s%.]*$"] = "^[%+]?%s*(%d+%.?%d*)%s+(.-)[%s%.]*$"
L["^(.-)%s+[%+:]?%s*(%d+%.?%d*)[%s%.]*$"] = "^(.-)%s+[%+:]?%s*(%d+%.?%d*)[%s%.]*$"
L["^(%d+) armor$"] = "^(%d+) armor$"
L["^(%d+) block$"] = "^(%d+) block$"
L["speed (%d+%.?%d*)"] = "speed (%d+%.?%d*)"
L["^%((%d+%.?%d*) damage per second%)$"] = "^%((%d+%.?%d*) damage per second%)$"
L["^%((%d+%.?%d*) dps%)$"] = "^%((%d+%.?%d*) dps%)$"
L["^(%d+)%s?[-~]%s?(%d+) damage$"] = "^(%d+)%s?[-~]%s?(%d+) damage$"
L["scope %([%+:]*(%d+) (.*)%)"] = "scope %([%+:]*(%d+) (.*)%)"
L["enchant:? [%+:]*(%d+) (.*)"] = "enchant:? [%+:]*(%d+) (.*)"

-- Equip/Use/Proc Patterns (English Defaults)
L["damage and healing.-(%d+)"] = "damage and healing.-(%d+)"
L["healing done.-(%d+)"] = "healing done.-(%d+)"
L["spell penetration.-(%d+)"] = "spell penetration.-(%d+)"
L["restores (%d+) mana"] = "restores (%d+) mana"
L["spell hit rating.-(%d+)"] = "spell hit rating.-(%d+)"
L["ranged hit rating.-(%d+)"] = "ranged hit rating.-(%d+)"
L["hit rating.-(%d+)"] = "hit rating.-(%d+)"
L["spell crit.-(%d+)"] = "spell crit.-(%d+)"
L["ranged crit.-(%d+)"] = "ranged crit.-(%d+)"
L["critical strike rating.-(%d+)"] = "critical strike rating.-(%d+)"
L["ranged attack power.-(%d+)"] = "ranged attack power.-(%d+)"
L["feral attack power.-(%d+)"] = "feral attack power.-(%d+)"
L["attack power.-(%d+)"] = "attack power.-(%d+)"
L["expertise rating.-(%d+)"] = "expertise rating.-(%d+)"
L["armor penetration.-(%d+)"] = "armor penetration.-(%d+)"
L["block value.-(%d+)"] = "block value.-(%d+)"
L["block rating.-(%d+)"] = "block rating.-(%d+)"
L["defense rating.-(%d+)"] = "defense rating.-(%d+)"
L["dodge rating.-(%d+)"] = "dodge rating.-(%d+)"
L["parry rating.-(%d+)"] = "parry rating.-(%d+)"
L["resilience.-(%d+)"] = "resilience.-(%d+)"
L["spell haste.-(%d+)"] = "spell haste.-(%d+)"
L["haste rating.-(%d+)"] = "haste rating.-(%d+)"
L["shadow damage.-(%d+)"] = "shadow damage.-(%d+)"
L["fire damage.-(%d+)"] = "fire damage.-(%d+)"
L["frost damage.-(%d+)"] = "frost damage.-(%d+)"
L["arcane damage.-(%d+)"] = "arcane damage.-(%d+)"
L["nature damage.-(%d+)"] = "nature damage.-(%d+)"
L["holy damage.-(%d+)"] = "holy damage.-(%d+)"
L["healing.-up to (%d+).-damage.-up to (%d+)"] = "healing.-up to (%d+).-damage.-up to (%d+)"
L["adds (%d+) weapon damage"] = "adds (%d+) weapon damage"
L["adds (%d+) damage"] = "adds (%d+) damage"
L["improves your (.*) by (%d+)%%%.?"] = "improves your (.*) by (%d+)%%%.?"
L["increases your (.*) by (%d+)%%%.?"] = "increases your (.*) by (%d+)%%%.?"
L["increases (.*) by (%d+)%%%.?"] = "increases (.*) by (%d+)%%%.?"
L["improves your (.*) by (%d+)%.?"] = "improves your (.*) by (%d+)%.?"
L["improves (.*) by (%d+)%.?"] = "improves (.*) by (%d+)%.?"
L["increases your (.*) by (%d+)%.?"] = "increases your (.*) by (%d+)%.?"
L["increases (.*) by up to (%d+)%.?"] = "increases (.*) by up to (%d+)%.?"
L["increases (.*) by (%d+)%.?"] = "increases (.*) by (%d+)%.?"
L["^%+?%s*(%d+)%%? (.*)$"] = "^%+?%s*(%d+)%%? (.*)$"
L["^(.-) %+(%d+)%%?$"] = "^(.-) %+(%d+)%%?$"
L["^%+(%d+) (.*) for (%d+) sec"] = "^%+(%d+) (.*) for (%d+) sec"
L["grants (%d+) (.*) for (%d+) sec"] = "grants (%d+) (.*) for (%d+) sec"
L["gain (%d+) (.*) for (%d+) sec"] = "gain (%d+) (.*) for (%d+) sec"
L["increases (.*) by (%d+) for (%d+) sec"] = "increases (.*) by (%d+) for (%d+) sec"
L["increases your (.*) by (%d+)$"] = "increases your (.*) by (%d+)$"
L["chance on melee or ranged hit to gain (%d+) (.*) for (%d+) sec"] = "chance on melee or ranged hit to gain (%d+) (.*) for (%d+) sec"
L["chance on spell critical hit to gain (%d+) (.*) for (%d+) sec"] = "chance on spell critical hit to gain (%d+) (.*) for (%d+) sec"
L["chance on spell cast to gain (%d+) (.*) for (%d+) sec"] = "chance on spell cast to gain (%d+) (.*) for (%d+) sec"
L["for (%d+) to (%d+) .*damage"] = "for (%d+) to (%d+) .*damage"
L["inflicts (%d+) to (%d+) .*damage"] = "inflicts (%d+) to (%d+) .*damage"
L["for (%d+) .*damage"] = "for (%d+) .*damage"
L["inflicts (%d+) .*damage"] = "inflicts (%d+) .*damage"
L["deals (%d+) .*damage"] = "deals (%d+) .*damage"
L["blasts (.*) for (%d+)"] = "blasts (.*) for (%d+)"
L["chance to strike your enemy for (%d+) to (%d+) .*damage"] = "chance to strike your enemy for (%d+) to (%d+) .*damage"
L["chance to blast your target for (%d+) to (%d+) .*damage"] = "chance to blast your target for (%d+) to (%d+) .*damage"
L["steals (%d+) life"] = "steals (%d+) life"
L["restores (%d+) health"] = "restores (%d+) health"
L["blasts your enemy"] = "blasts your enemy"
L["^%+(%d+) (.*)$"] = "^%+(%d+) (.*)$"
L["increases (.*) by up to (%d+) for (%d+) sec"] = "increases (.*) by up to (%d+) for (%d+) sec"
L["restores (%d+) to (%d+) mana"] = "restores (%d+) to (%d+) mana"
L["restores (%d+) to (%d+) health"] = "restores (%d+) to (%d+) health"

-- Data Map Keys (Standard)
L["strength"] = "strength"
L["agility"] = "agility"
L["stamina"] = "stamina"
L["intellect"] = "intellect"
L["spirit"] = "spirit"
L["armor"] = "armor"
L["block"] = "block"
L["block value"] = "block value"
L["speed"] = "speed"
L["damage per second"] = "damage per second"
L["dps"] = "dps"
L["shadow resistance"] = "shadow resistance"
L["fire resistance"] = "fire resistance"
L["frost resistance"] = "frost resistance"
L["arcane resistance"] = "arcane resistance"
L["nature resistance"] = "nature resistance"
L["attack power"] = "attack power"
L["healing spells"] = "healing spells"
L["healing"] = "healing"
L["spell damage"] = "spell damage"
L["spell power"] = "spell power"
L["shadow damage"] = "shadow damage"
L["fire damage"] = "fire damage"
L["frost damage"] = "frost damage"
L["arcane damage"] = "arcane damage"
L["nature damage"] = "nature damage"
L["holy damage"] = "holy damage"
L["shadow spell damage"] = "shadow spell damage"
L["fire spell damage"] = "fire spell damage"
L["frost spell damage"] = "frost spell damage"
L["arcane spell damage"] = "arcane spell damage"
L["nature spell damage"] = "nature spell damage"
L["holy spell damage"] = "holy spell damage"
L["spell damage and healing"] = "spell damage and healing"
L["damage and healing spells"] = "damage and healing spells"
L["ranged attack power"] = "ranged attack power"
L["spell penetration"] = "spell penetration"
L["all stats"] = "all stats"
L["magic resistance"] = "magic resistance"
L["mana"] = "mana"
L["health"] = "health"
L["hp"] = "hp"
L["mp"] = "mp"
L["dodge rating"] = "dodge rating"
L["parry rating"] = "parry rating"
L["block rating"] = "block rating"
L["hit rating"] = "hit rating"
L["crit rating"] = "crit rating"
L["critical strike rating"] = "critical strike rating"
L["haste rating"] = "haste rating"
L["resilience rating"] = "resilience rating"
L["defense rating"] = "defense rating"
L["expertise rating"] = "expertise rating"
L["armor penetration rating"] = "armor penetration rating"

-- Green Text Map Keys
L["chance to hit"] = "chance to hit"
L["chance to get a critical strike"] = "chance to get a critical strike"
L["spell hit rating"] = "spell hit rating"
L["chance to hit with spells"] = "chance to hit with spells"
L["spell critical strike rating"] = "spell critical strike rating"
L["critical strike with spells"] = "critical strike with spells"
L["chance to get a critical strike with spells"] = "chance to get a critical strike with spells"
L["spell haste rating"] = "spell haste rating"
L["magical resistances"] = "magical resistances"
L["magical resistances of your spell targets"] = "magical resistances of your spell targets"
L["increased defense"] = "increased defense"
L["defense"] = "defense"
L["chance to dodge"] = "chance to dodge"
L["chance to parry"] = "chance to parry"
L["chance to block"] = "chance to block"
L["shield block value"] = "shield block value"
L["the block value of your shield"] = "the block value of your shield"
L["all resistances"] = "all resistances"
L["resistance to all schools of magic"] = "resistance to all schools of magic"
L["attack power in cat"] = "attack power in cat"
L["feral attack power"] = "feral attack power"
L["mana per 5 sec"] = "mana per 5 sec"
L["health per 5 sec"] = "health per 5 sec"
L["healing done by spells and effects"] = "healing done by spells and effects"
L["healing done by magical spells and effects"] = "healing done by magical spells and effects"
L["spell damage rating"] = "spell damage rating"
L["damage done by magical spells and effects"] = "damage done by magical spells and effects"
L["damage and healing done by magical spells and effects"] = "damage and healing done by magical spells and effects"
L["damage and healing done by magical spells and effects by up to"] = "damage and healing done by magical spells and effects by up to"
L["damage done by shadow spells and effects"] = "damage done by shadow spells and effects"
L["damage done by fire spells and effects"] = "damage done by fire spells and effects"
L["damage done by frost spells and effects"] = "damage done by frost spells and effects"
L["damage done by arcane spells and effects"] = "damage done by arcane spells and effects"
L["damage done by nature spells and effects"] = "damage done by nature spells and effects"
L["damage done by holy spells and effects"] = "damage done by holy spells and effects"
L["swords"] = "swords"
L["axes"] = "axes"
L["maces"] = "maces"
L["daggers"] = "daggers"
L["bows"] = "bows"
L["crossbows"] = "crossbows"
L["guns"] = "guns"
L["staves"] = "staves"
L["polearms"] = "polearms"
L["two-handed swords"] = "two-handed swords"
L["two-handed axes"] = "two-handed axes"
L["two-handed maces"] = "two-handed maces"
L["skill with swords"] = "skill with swords"
L["skill with axes"] = "skill with axes"
L["skill with maces"] = "skill with maces"
L["skill with bows"] = "skill with bows"
L["skill with guns"] = "skill with guns"
L["skill with daggers"] = "skill with daggers"
L["skill with crossbows"] = "skill with crossbows"
L["skill with staves"] = "skill with staves"
L["skill with polearms"] = "skill with polearms"
L["ranged critical strike rating"] = "ranged critical strike rating"
L["ranged hit rating"] = "ranged hit rating"
L["ranged haste rating"] = "ranged haste rating"
L["shield block rating"] = "shield block rating"
L["your pet's armor"] = "your pet's armor"
L["your pet's attack power"] = "your pet's attack power"
L["your pet's damage"] = "your pet's damage"
L["chance to resist mechanic mechanics"] = "chance to resist mechanic mechanics"
L["^(.*)%s+%(?(%d+)/(%d+)%)?$"] = "^(.*)%s+%(?(%d+)/(%d+)%)?$"