local addonName, MSC = ...
local L = {}
setmetatable(L, {
    __index = function(t, k)
        local v = tostring(k)
        rawset(t, k, v)
        return v
    end
})

MSC.L = L

-- =============================================================
-- ENGLISH (Default)
-- =============================================================

-- =============================================================
-- Init
-- =============================================================
L["|cff00ff00Sharpie's Gear Judge:|r Loaded %s"] = "|cff00ff00Sharpie's Gear Judge:|r Loaded %s"

-- =============================================================
-- Conflict Manager
-- =============================================================
L["Yes, Disable & Reload"] = "Yes, Disable & Reload"
L["No, Keep Both"] = "No, Keep Both"
L["|cff00FF00[SGJ]|r: Pawn settings not found yet."] = "|cff00FF00[SGJ]|r: Pawn settings not found yet."
L["|cff00FF00Sharpie's Gear Judge|r\n\nI see RestedXP is active.\n\nIt is currently showing its own gear tips.\n\nDo you want me to disable their **Item Upgrade** setting?"] = "|cff00FF00Sharpie's Gear Judge|r\n\nI see RestedXP is active.\n\nIt is currently showing its own gear tips.\n\nDo you want me to disable their **Item Upgrade** setting?"
L["|cff00FF00Sharpie's Gear Judge|r\n\nI see Zygor Guides is active.\n\nIt adds its own 'Gear Score' to tooltips.\n\nDo you want me to disable their **Auto Gear** system?"] = "|cff00FF00Sharpie's Gear Judge|r\n\nI see Zygor Guides is active.\n\nIt adds its own 'Gear Score' to tooltips.\n\nDo you want me to disable their **Auto Gear** system?"
L["|cff00FF00Sharpie's Gear Judge|r\n\nI see Pawn is active.\n\nFor conflict-free use, we recommend disabling **Pawn's Tooltip Upgrades** so they don't overlap with our Verdict.\n\nDisable Pawn tooltip info?"] = "|cff00FF00Sharpie's Gear Judge|r\n\nI see Pawn is active.\n\nFor conflict-free use, we recommend disabling **Pawn's Tooltip Upgrades** so they don't overlap with our Verdict.\n\nDisable Pawn tooltip info?"

-- =============================================================
-- Evaluator
-- =============================================================
L["Bag Item"] = "Bag Item"
L["Cap"] = "Cap"
L["Exp"] = "Exp"
L["Def"] = "Def"

-- Context Messages
L["|cffff0000(Not 2Hander)|r"] = "|cffff0000(Not 2Hander)|r"
L["|cff00ff00(w/ %s)|r"] = "|cff00ff00(w/ %s)|r"
L["|cffff0000(No OH found)|r"] = "|cffff0000(No OH found)|r"
L["|cffff0000(No MH found)|r"] = "|cffff0000(No MH found)|r"
L["|cff00ff00(Set Bonus %s)|r"] = "|cff00ff00(Set Bonus %s)|r"

-- Cap Warnings (Format Strings)
L[" |cffff0000(Cap %.1f %s)|r"] = " |cffff0000(Cap %.1f %s)|r"
L[" |cffff0000(Cap %.1f Def)|r"] = " |cffff0000(Cap %.1f Def)|r"

-- =============================================================
-- Database
-- =============================================================
-- STAT NAMES 
L["Resilience"] = "Resilience"
L["Haste"] = "Haste"
L["Spell Haste"] = "Spell Haste"
L["Expertise"] = "Expertise"
L["Armor Pen"] = "Armor Pen"
L["Spell Pen"] = "Spell Pen"
L["Feral AP"] = "Feral AP"
L["PvP Utility"] = "PvP Utility"
L["Armor"] = "Armor"
L["Agility"] = "Agility"
L["Strength"] = "Strength"
L["Intellect"] = "Intellect"
L["Spirit"] = "Spirit"
L["Stamina"] = "Stamina"
L["Health"] = "Health"
L["Mana"] = "Mana"
L["Spell Power"] = "Spell Power"
L["Healing"] = "Healing"
L["Mp5"] = "Mp5"
L["DPS"] = "DPS"
L["Attack Power"] = "Attack Power"
L["Ranged AP"] = "Ranged AP"
L["Hp5"] = "Hp5"
L["Crit"] = "Crit"
L["Spell Crit"] = "Spell Crit"
L["Hit"] = "Hit"
L["Spell Hit"] = "Spell Hit"
L["Crit (from Agi)"] = "Crit (from Agi)"
L["Spell Crit (from Int)"] = "Spell Crit (from Int)"
L["Defense"] = "Defense"
L["Dodge"] = "Dodge"
L["Parry"] = "Parry"
L["Block %"] = "Block %"
L["Block Value"] = "Block Value"
L["Shadow Dmg"] = "Shadow Dmg"
L["Fire Dmg"] = "Fire Dmg"
L["Frost Dmg"] = "Frost Dmg"
L["Arcane Dmg"] = "Arcane Dmg"
L["Nature Dmg"] = "Nature Dmg"
L["Holy Dmg"] = "Holy Dmg"
L["Shadow Res"] = "Shadow Res"
L["Fire Res"] = "Fire Res"
L["Frost Res"] = "Frost Res"
L["Nature Res"] = "Nature Res"
L["Arcane Res"] = "Arcane Res"
L["All Res"] = "All Res"
L["Speed"] = "Speed"
L["Weapon DPS"] = "Weapon DPS"
L["Wand DPS"] = "Wand DPS"

-- PROFILE NAMES
L["Starter (1-20)"] = "Starter (1-20)"
L["Standard Leveling (21-40)"] = "Standard Leveling (21-40)"
L["Standard Leveling (41-51)"] = "Standard Leveling (41-51)"
L["Standard Leveling (52-59)"] = "Standard Leveling (52-59)"
L["Standard Leveling (Outland)"] = "Standard Leveling (Outland)"

-- ENCHANT NAMES
L["Mongoose"] = "Mongoose"
L["Sunfire"] = "Sunfire"
L["Soulfrost"] = "Soulfrost"
L["Executioner"] = "Executioner"
L["Major Spellpower"] = "Major Spellpower"
L["Major Healing"] = "Major Healing"
L["Sunfire (Healing)"] = "Sunfire (Healing)"
L["Major Intellect"] = "Major Intellect"
L["Savagery"] = "Savagery"
L["Major Agility"] = "Major Agility"
L["Greater Agility (2H)"] = "Greater Agility (2H)"
L["Spell Surge"] = "Spell Surge"
L["Potency"] = "Potency"
L["Crusader"] = "Crusader"
L["Fiery Weapon"] = "Fiery Weapon"
L["Weapon Dmg +5"] = "Weapon Dmg +5"
L["Spellpower +30"] = "Spellpower +30"
L["Healing +55"] = "Healing +55"
L["Unholy Weapon"] = "Unholy Weapon"
L["Major Strength (+15)"] = "Major Strength (+15)"
L["Lifestealing"] = "Lifestealing"
L["Lesser Striking (+3)"] = "Lesser Striking (+3)"
L["Icy Chill"] = "Icy Chill"
L["Agility +15"] = "Agility +15"
L["Major Striking (+4)"] = "Major Striking (+4)"
L["Superior Striking (+5)"] = "Superior Striking (+5)"
L["Greater Striking (+4)"] = "Greater Striking (+4)"
L["Striking (+3)"] = "Striking (+3)"
L["Lesser Striking (+2)"] = "Lesser Striking (+2)"
L["Minor Striking (+1)"] = "Minor Striking (+1)"
L["Demonslaying"] = "Demonslaying"
L["Lesser Beastslayer"] = "Lesser Beastslayer"
L["Minor Beastslayer"] = "Minor Beastslayer"
L["Adamantite Scope"] = "Adamantite Scope"
L["Khorium Scope"] = "Khorium Scope"
L["Stabilized Eternium Scope"] = "Stabilized Eternium Scope"
L["Sniper Scope"] = "Sniper Scope"
L["Accurate Scope"] = "Accurate Scope"
L["Standard Scope"] = "Standard Scope"
L["Biznicks Accurascope"] = "Biznicks Accurascope"
L["Major Stamina"] = "Major Stamina"
L["Shield Block"] = "Shield Block"
L["Lesser Stamina"] = "Lesser Stamina"
L["Greater Spirit"] = "Greater Spirit"
L["Greater Stamina"] = "Greater Stamina"
L["Felsteel Shield Spike"] = "Felsteel Shield Spike"
L["Thorium Shield Spike"] = "Thorium Shield Spike"
L["Mithril Shield Spike"] = "Mithril Shield Spike"
L["Iron Shield Spike"] = "Iron Shield Spike"
L["Glyph of Power"] = "Glyph of Power"
L["Glyph of Ferocity"] = "Glyph of Ferocity"
L["Glyph of the Defender"] = "Glyph of the Defender"
L["Glyph of Renewal"] = "Glyph of Renewal"
L["Glyph of the Gladiator"] = "Glyph of the Gladiator"
L["Glyph of the Outcast"] = "Glyph of the Outcast"
L["Lesser Arcanum (Agi)"] = "Lesser Arcanum (Agi)"
L["Lesser Arcanum (Int)"] = "Lesser Arcanum (Int)"
L["Lesser Arcanum (Str)"] = "Lesser Arcanum (Str)"
L["Syncretist's Sigil"] = "Syncretist's Sigil"
L["Greater Inscription of the Orb"] = "Greater Inscription of the Orb"
L["Greater Inscription of Vengeance"] = "Greater Inscription of Vengeance"
L["Greater Inscription of the Knight"] = "Greater Inscription of the Knight"
L["Greater Inscription of the Oracle"] = "Greater Inscription of the Oracle"
L["Inscription of the Orb"] = "Inscription of the Orb"
L["Inscription of Vengeance"] = "Inscription of Vengeance"
L["Inscription of the Knight"] = "Inscription of the Knight"
L["Inscription of the Oracle"] = "Inscription of the Oracle"
L["Zandalar Signet of Mojo"] = "Zandalar Signet of Mojo"
L["Zandalar Signet of Might"] = "Zandalar Signet of Might"
L["Zandalar Signet of Serenity"] = "Zandalar Signet of Serenity"
L["Greater Agility (+12)"] = "Greater Agility (+12)"
L["Spell Penetration"] = "Spell Penetration"
L["Steelweave"] = "Steelweave"
L["Major Armor"] = "Major Armor"
L["Lesser Agility (+3)"] = "Lesser Agility (+3)"
L["Greater Resistance"] = "Greater Resistance"
L["Superior Defense (+70)"] = "Superior Defense (+70)"
L["Greater Defense (+50)"] = "Greater Defense (+50)"
L["Minor Agility (+1)"] = "Minor Agility (+1)"
L["Subtlety (-2% Threat)"] = "Subtlety (-2% Threat)"
L["Dodge (+1%)"] = "Dodge (+1%)"
L["Major Resistance (+7)"] = "Major Resistance (+7)"
L["Greater Shadow Resistance"] = "Greater Shadow Resistance"
L["Subtlety"] = "Subtlety"
L["Exceptional Stats (+6)"] = "Exceptional Stats (+6)"
L["Major Health (+150)"] = "Major Health (+150)"
L["Major Resilience"] = "Major Resilience"
L["Restore Mana Prime"] = "Restore Mana Prime"
L["Greater Stats (+4)"] = "Greater Stats (+4)"
L["Minor Stats (+1)"] = "Minor Stats (+1)"
L["Major Health (+100)"] = "Major Health (+100)"
L["Stats (+3)"] = "Stats (+3)"
L["Lesser Stats (+2)"] = "Lesser Stats (+2)"
L["Major Mana (+100)"] = "Major Mana (+100)"
L["Superior Health (+50)"] = "Superior Health (+50)"
L["Minor Health (+5)"] = "Minor Health (+5)"
L["Lesser Health (+15)"] = "Lesser Health (+15)"
L["Health (+25)"] = "Health (+25)"
L["Greater Health (+35)"] = "Greater Health (+35)"
L["Mana (+50)"] = "Mana (+50)"
L["Lesser Mana (+30)"] = "Lesser Mana (+30)"
L["Brawn (+12 Str)"] = "Brawn (+12 Str)"
L["Spellpower (+15)"] = "Spellpower (+15)"
L["Major Healing (+30)"] = "Major Healing (+30)"
L["Assault (+24 AP)"] = "Assault (+24 AP)"
L["Major Defense"] = "Major Defense"
L["Fortitude (+12 Stam)"] = "Fortitude (+12 Stam)"
L["Intellect +7"] = "Intellect +7"
L["Spirit +9"] = "Spirit +9"
L["Minor Strength (+1)"] = "Minor Strength (+1)"
L["Superior Strength (+9)"] = "Superior Strength (+9)"
L["Superior Stamina (+9)"] = "Superior Stamina (+9)"
L["Mana Regen (+4mp5)"] = "Mana Regen (+4mp5)"
L["Healing Power (+24)"] = "Healing Power (+24)"
L["Major Strength (+12)"] = "Major Strength (+12)"
L["Major Intellect (+12)"] = "Major Intellect (+12)"
L["Minor Spirit (+1)"] = "Minor Spirit (+1)"
L["Lesser Spirit (+3)"] = "Lesser Spirit (+3)"
L["Spirit (+5)"] = "Spirit (+5)"
L["Greater Spirit (+7)"] = "Greater Spirit (+7)"
L["Minor Stamina (+1)"] = "Minor Stamina (+1)"
L["Lesser Stamina (+3)"] = "Lesser Stamina (+3)"
L["Stamina (+5)"] = "Stamina (+5)"
L["Greater Stamina (+7)"] = "Greater Stamina (+7)"
L["Superior Agility (+15)"] = "Superior Agility (+15)"
L["Major Spellpower (+20)"] = "Major Spellpower (+20)"
L["Major Healing (+35)"] = "Major Healing (+35)"
L["Assault (+26 AP)"] = "Assault (+26 AP)"
L["Threat (+Hit)"] = "Threat (+Hit)"
L["Blast (+Crit)"] = "Blast (+Crit)"
L["Agility +7"] = "Agility +7"
L["Greater Strength (+7)"] = "Greater Strength (+7)"
L["Greater Agility (Classic +7)"] = "Greater Agility (Classic +7)"
L["Agility (+5)"] = "Agility (+5)"
L["Riding Skill"] = "Riding Skill"
L["Strength (+5)"] = "Strength (+5)"
L["Shadow Power (+20)"] = "Shadow Power (+20)"
L["Frost Power (+20)"] = "Frost Power (+20)"
L["Fire Power (+20)"] = "Fire Power (+20)"
L["Healing Power (+30)"] = "Healing Power (+30)"
L["Precision (+15 Hit)"] = "Precision (+15 Hit)"
L["Spell Strike (+15 Hit)"] = "Spell Strike (+15 Hit)"
L["Glove Reinforcements"] = "Glove Reinforcements"
L["Runic Spellthread"] = "Runic Spellthread"
L["Golden Spellthread"] = "Golden Spellthread"
L["Nethercobra Leg Armor"] = "Nethercobra Leg Armor"
L["Nethercleft Leg Armor"] = "Nethercleft Leg Armor"
L["Cobrahide Leg Armor"] = "Cobrahide Leg Armor"
L["Mystic Spellthread"] = "Mystic Spellthread"
L["Clefthide Leg Armor"] = "Clefthide Leg Armor"
L["Lesser Arcanum of Rumination"] = "Lesser Arcanum of Rumination"
L["Lesser Arcanum of Constitution"] = "Lesser Arcanum of Constitution"
L["Boar's Speed"] = "Boar's Speed"
L["Cat's Swiftness"] = "Cat's Swiftness"
L["Surefooted"] = "Surefooted"
L["Minor Speed"] = "Minor Speed"
L["Surefooted (+5% Resist)"] = "Surefooted (+5% Resist)"
L["Dexterity (+12 Agi)"] = "Dexterity (+12 Agi)"
L["Spellpower"] = "Spellpower"
L["Healing Power"] = "Healing Power"
L["Stats"] = "Stats"
L["Striking"] = "Striking"
L["Minor Haste"] = "Minor Haste"
L["Winter's Might (+7 SP)"] = "Winter's Might (+7 SP)"
L["Lesser Intellect (+6)"] = "Lesser Intellect (+6)"
L["Major Intellect (+22)"] = "Major Intellect (+22)"
L["Major Spirit (+20)"] = "Major Spirit (+20)"
L["Impact (+5 Dmg)"] = "Impact (+5 Dmg)"
L["Lesser Absorption"] = "Lesser Absorption"
L["Power of the Scourge"] = "Power of the Scourge"
L["Fortitude of the Scourge"] = "Fortitude of the Scourge"
L["Might of the Scourge"] = "Might of the Scourge"
L["Resilience of the Scourge"] = "Resilience of the Scourge"
L["CC Break (Rank 1)"] = "CC Break (Rank 1)"
L["CC Break (Rank 2)"] = "CC Break (Rank 2)"
L["CC Break (Rank 3)"] = "CC Break (Rank 3)"

-- GEM NAMES
L["Void Sphere"] = "Void Sphere"
L["Bold Living Ruby"] = "Bold Living Ruby"
L["Delicate Living Ruby"] = "Delicate Living Ruby"
L["Runed Living Ruby"] = "Runed Living Ruby"
L["Bright Living Ruby"] = "Bright Living Ruby"
L["Subtle Living Ruby"] = "Subtle Living Ruby"
L["Flashing Living Ruby"] = "Flashing Living Ruby"
L["Teardrop Living Ruby"] = "Teardrop Living Ruby"
L["Runed Ornate Ruby"] = "Runed Ornate Ruby"
L["Bold Ornate Ruby"] = "Bold Ornate Ruby"
L["Solid Star of Elune"] = "Solid Star of Elune"
L["Sparkling Star of Elune"] = "Sparkling Star of Elune"
L["Lustrous Star of Elune"] = "Lustrous Star of Elune"
L["Stormy Star of Elune"] = "Stormy Star of Elune"
L["Eye of the Sea"] = "Eye of the Sea"
L["Rigid Dawnstone"] = "Rigid Dawnstone"
L["Smooth Dawnstone"] = "Smooth Dawnstone"
L["Brilliant Dawnstone"] = "Brilliant Dawnstone"
L["Thick Dawnstone"] = "Thick Dawnstone"
L["Mystic Dawnstone"] = "Mystic Dawnstone"
L["Gleaming Dawnstone"] = "Gleaming Dawnstone"
L["Great Dawnstone"] = "Great Dawnstone"
L["Smooth Ornate Dawnstone"] = "Smooth Ornate Dawnstone"
L["Inscribed Noble Topaz"] = "Inscribed Noble Topaz"
L["Etched Noble Topaz"] = "Etched Noble Topaz"
L["Potent Noble Topaz"] = "Potent Noble Topaz"
L["Veiled Noble Topaz"] = "Veiled Noble Topaz"
L["Glinting Noble Topaz"] = "Glinting Noble Topaz"
L["Luminous Noble Topaz"] = "Luminous Noble Topaz"
L["Inscribed Ornate Topaz"] = "Inscribed Ornate Topaz"
L["Sovereign Nightseye"] = "Sovereign Nightseye"
L["Shifting Nightseye"] = "Shifting Nightseye"
L["Glowing Nightseye"] = "Glowing Nightseye"
L["Purified Nightseye"] = "Purified Nightseye"
L["Royal Nightseye"] = "Royal Nightseye"
L["Balanced Nightseye"] = "Balanced Nightseye"
L["Purified Shadow Pearl"] = "Purified Shadow Pearl"
L["Regal Nightseye"] = "Regal Nightseye"
L["Enduring Talasite"] = "Enduring Talasite"
L["Dazzling Talasite"] = "Dazzling Talasite"
L["Jagged Talasite"] = "Jagged Talasite"
L["Vivid Talasite"] = "Vivid Talasite"
L["Steady Talasite"] = "Steady Talasite"
L["Relentless Earthstorm"] = "Relentless Earthstorm"
L["Chaotic Skyfire"] = "Chaotic Skyfire"
L["Mystical Skyfire"] = "Mystical Skyfire"
L["Powerful Earthstorm"] = "Powerful Earthstorm"
L["Brutal Earthstorm"] = "Brutal Earthstorm"
L["Insightful Earthstorm"] = "Insightful Earthstorm"
L["Destructive Skyfire"] = "Destructive Skyfire"
L["Swift Starfire"] = "Swift Starfire"
L["Bracing Earthstorm"] = "Bracing Earthstorm"
L["Bold Crimson Spinel"] = "Bold Crimson Spinel"
L["Delicate Crimson Spinel"] = "Delicate Crimson Spinel"
L["Runed Crimson Spinel"] = "Runed Crimson Spinel"
L["Teardrop Crimson Spinel"] = "Teardrop Crimson Spinel"
L["Solid Empyrean Sapphire"] = "Solid Empyrean Sapphire"
L["Sparkling Empyrean Sapphire"] = "Sparkling Empyrean Sapphire"
L["Stormy Empyrean Sapphire"] = "Stormy Empyrean Sapphire"
L["Brilliant Lionseye"] = "Brilliant Lionseye"
L["Smooth Lionseye"] = "Smooth Lionseye"
L["Rigid Lionseye"] = "Rigid Lionseye"
L["Thick Lionseye"] = "Thick Lionseye"
L["Mystic Lionseye"] = "Mystic Lionseye"
L["Great Lionseye"] = "Great Lionseye"
L["Inscribed Pyrestone"] = "Inscribed Pyrestone"
L["Potent Pyrestone"] = "Potent Pyrestone"
L["Luminous Pyrestone"] = "Luminous Pyrestone"
L["Glinting Pyrestone"] = "Glinting Pyrestone"
L["Veiled Pyrestone"] = "Veiled Pyrestone"
L["Wicked Pyrestone"] = "Wicked Pyrestone"
L["Sovereign Shadowsong Amethyst"] = "Sovereign Shadowsong Amethyst"
L["Shifting Shadowsong Amethyst"] = "Shifting Shadowsong Amethyst"
L["Glowing Shadowsong Amethyst"] = "Glowing Shadowsong Amethyst"
L["Royal Shadowsong Amethyst"] = "Royal Shadowsong Amethyst"
L["Purified Shadowsong Amethyst"] = "Purified Shadowsong Amethyst"
L["Enduring Seaspray Emerald"] = "Enduring Seaspray Emerald"
L["Jagged Seaspray Emerald"] = "Jagged Seaspray Emerald"
L["Crimson Sun"] = "Crimson Sun"
L["Don Julio's Heart"] = "Don Julio's Heart"
L["Kailee's Rose"] = "Kailee's Rose"
L["Don Amancio's Heart"] = "Don Amancio's Heart"
L["Delicate Fire Ruby"] = "Delicate Fire Ruby"
L["Falling Star"] = "Falling Star"
L["Sparkling Falling Star"] = "Sparkling Falling Star"
L["Lustrous Falling Star"] = "Lustrous Falling Star"
L["Stormy Falling Star"] = "Stormy Falling Star"
L["Blood of Amber"] = "Blood of Amber"
L["Stone of Blades"] = "Stone of Blades"
L["Brilliant Bladestone"] = "Brilliant Bladestone"
L["Great Bladestone"] = "Great Bladestone"
L["Rigid Bladestone"] = "Rigid Bladestone"
L["Mystic Bladestone"] = "Mystic Bladestone"
L["Facet of Eternity"] = "Facet of Eternity"
L["Quick Lionseye"] = "Quick Lionseye"
L["Reckless Pyrestone"] = "Reckless Pyrestone"
L["Luminous Fire Opal"] = "Luminous Fire Opal"
L["Glinting Fire Opal"] = "Glinting Fire Opal"
L["Etched Fire Opal"] = "Etched Fire Opal"
L["Shining Fire Opal"] = "Shining Fire Opal"
L["Deadly Fire Opal"] = "Deadly Fire Opal"
L["Potent Fire Opal"] = "Potent Fire Opal"
L["Iridescent Fire Opal"] = "Iridescent Fire Opal"
L["Resplendent Fire Opal"] = "Resplendent Fire Opal"
L["Sovereign Tanzanite"] = "Sovereign Tanzanite"
L["Shifting Tanzanite"] = "Shifting Tanzanite"
L["Glowing Tanzanite"] = "Glowing Tanzanite"
L["Brutal Tanzanite"] = "Brutal Tanzanite"
L["Fluorescent Tanzanite"] = "Fluorescent Tanzanite"
L["Royal Tanzanite"] = "Royal Tanzanite"
L["Steady Seaspray Emerald"] = "Steady Seaspray Emerald"
L["Forceful Seaspray Emerald"] = "Forceful Seaspray Emerald"
L["Sundered Chrysoprase"] = "Sundered Chrysoprase"
L["Jagged Chrysoprase"] = "Jagged Chrysoprase"
L["Vivid Chrysoprase"] = "Vivid Chrysoprase"
L["Lambent Chrysoprase"] = "Lambent Chrysoprase"
L["Eternal Earthstorm"] = "Eternal Earthstorm"
L["Bold Blood Garnet"] = "Bold Blood Garnet"
L["Delicate Blood Garnet"] = "Delicate Blood Garnet"
L["Runed Blood Garnet"] = "Runed Blood Garnet"
L["Bright Blood Garnet"] = "Bright Blood Garnet"
L["Teardrop Blood Garnet"] = "Teardrop Blood Garnet"
L["Solid Azure Moonstone"] = "Solid Azure Moonstone"
L["Sparkling Azure Moonstone"] = "Sparkling Azure Moonstone"
L["Lustrous Azure Moonstone"] = "Lustrous Azure Moonstone"
L["Stormy Azure Moonstone"] = "Stormy Azure Moonstone"
L["Rigid Golden Draenite"] = "Rigid Golden Draenite"
L["Smooth Golden Draenite"] = "Smooth Golden Draenite"
L["Brilliant Golden Draenite"] = "Brilliant Golden Draenite"
L["Thick Golden Draenite"] = "Thick Golden Draenite"
L["Gleaming Golden Draenite"] = "Gleaming Golden Draenite"
L["Inscribed Flame Spessarite"] = "Inscribed Flame Spessarite"
L["Glinting Flame Spessarite"] = "Glinting Flame Spessarite"
L["Potent Flame Spessarite"] = "Potent Flame Spessarite"
L["Veiled Flame Spessarite"] = "Veiled Flame Spessarite"
L["Luminous Flame Spessarite"] = "Luminous Flame Spessarite"
L["Sovereign Shadow Draenite"] = "Sovereign Shadow Draenite"
L["Shifting Shadow Draenite"] = "Shifting Shadow Draenite"
L["Glowing Shadow Draenite"] = "Glowing Shadow Draenite"
L["Royal Shadow Draenite"] = "Royal Shadow Draenite"
L["Enduring Deep Peridot"] = "Enduring Deep Peridot"
L["Dazzling Deep Peridot"] = "Dazzling Deep Peridot"
L["Jagged Deep Peridot"] = "Jagged Deep Peridot"
L["Radiant Deep Peridot"] = "Radiant Deep Peridot"

-- TOOLTIP NOTES (Trinkets & Procs)
L["Use: 21 Avg Dodge (based on uptime)"] = "Use: 21 Avg Dodge (based on uptime)"
L["Use: Mana restore avg to ~15 mp5"] = "Use: Mana restore avg to ~15 mp5"
L["Use: 25 Avg SP (based on uptime)"] = "Use: 25 Avg SP (based on uptime)"
L["Use: 55 Avg AP (based on uptime)"] = "Use: 55 Avg AP (based on uptime)"
L["Use: 60 Avg AP + Pet Heal utility"] = "Use: 60 Avg AP + Pet Heal utility"
L["Use: 45 Avg AP + Pet Heal utility"] = "Use: 45 Avg AP + Pet Heal utility"
L["Use: ~34 Avg SP"] = "Use: ~34 Avg SP"
L["Use: 46 Avg AP (Defensive)"] = "Use: 46 Avg AP (Defensive)"
L["Use: ~23 mp5"] = "Use: ~23 mp5"
L["Use: 80 Avg AP"] = "Use: 80 Avg AP"
L["Use: Avg Summon Dmg"] = "Use: Avg Summon Dmg"
L["Use: 21 Avg SP"] = "Use: 21 Avg SP"
L["Use: 33 Avg AP"] = "Use: 33 Avg AP"
L["Use: 20 Avg SP"] = "Use: 20 Avg SP"
L["Use: 150 Avg Armor"] = "Use: 150 Avg Armor"
L["Use: 33 Avg SP"] = "Use: 33 Avg SP"
L["Use: 22.5 Avg AP"] = "Use: 22.5 Avg AP"
L["Use: HP valued flat"] = "Use: HP valued flat"
L["Use: 23 Avg SP"] = "Use: 23 Avg SP"
L["Use: 29 Avg AP"] = "Use: 29 Avg AP"
L["Use: 43 Avg HSP"] = "Use: 43 Avg HSP"
L["Use: 30 Avg AP"] = "Use: 30 Avg AP"
L["Use: ~12 mp5"] = "Use: ~12 mp5"
L["Use: ~14 Avg SP"] = "Use: ~14 Avg SP"
L["Use: 10 Avg AP (3.3% Uptime)"] = "Use: 10 Avg AP (3.3% Uptime)"
L["Use: Heal Valued as flat Stam"] = "Use: Heal Valued as flat Stam"
L["Use: 25 Avg SP"] = "Use: 25 Avg SP"
L["Use: 39 Avg HSP"] = "Use: 39 Avg HSP"
L["Use: 46 Avg AP"] = "Use: 46 Avg AP"
L["Use: 26 Avg SP"] = "Use: 26 Avg SP"
L["Use: 20 Avg Dodge"] = "Use: 20 Avg Dodge"
L["Use: Aggro reduction utility"] = "Use: Aggro reduction utility"
L["Use: Heal"] = "Use: Heal"
L["Use: 46.6 Avg Agi"] = "Use: 46.6 Avg Agi"
L["Proc: ~100 Avg Dodge (High Uptime)"] = "Proc: ~100 Avg Dodge (High Uptime)"
L["Use: 216 Avg Armor"] = "Use: 216 Avg Armor"
L["Use: 600 ArP (Avg 100)"] = "Use: 600 ArP (Avg 100)"
L["Use: 22 Avg SP"] = "Use: 22 Avg SP"
L["Use: 16.6 Avg SP"] = "Use: 16.6 Avg SP"
L["Use: Absorb valued as Health"] = "Use: Absorb valued as Health"
L["Use: Heal avg to 15 BV"] = "Use: Heal avg to 15 BV"
L["Proc: 38 Avg Haste"] = "Proc: 38 Avg Haste"
L["Proc: 50 Avg AP"] = "Proc: 50 Avg AP"
L["Use: 21 Avg Haste"] = "Use: 21 Avg Haste"
L["Proc: ~15 mp5"] = "Proc: ~15 mp5"
L["Proc: 300 AP (Internal CD)"] = "Proc: 300 AP (Internal CD)"
L["Use: Absorb valued as Stam"] = "Use: Absorb valued as Stam"
L["Proc: ~19 Avg SP"] = "Proc: ~19 Avg SP"
L["Use: 14 Avg Agi"] = "Use: 14 Avg Agi"
L["Proc: 160 Haste (15% spell proc) = ~26 Avg"] = "Proc: 160 Haste (15% spell proc) = ~26 Avg"
L["Proc: ~21 mp5"] = "Proc: ~21 mp5"
L["Proc: ~65 Avg AP"] = "Proc: ~65 Avg AP"
L["Proc: 108 Avg Haste"] = "Proc: 108 Avg Haste"
L["Use: 49.5 Avg HSP"] = "Use: 49.5 Avg HSP"
L["Use: 170 SP"] = "Use: 170 SP"
L["Use: 300 Dodge"] = "Use: 300 Dodge"
L["Use: 22 Avg mp5"] = "Use: 22 Avg mp5"
L["Proc: Chance to reduce mana cost avg to 45 mp5"] = "Proc: Chance to reduce mana cost avg to 45 mp5"
L["Proc: Lightning Capacitor Dmg avg to 55 SP"] = "Proc: Lightning Capacitor Dmg avg to 55 SP"
L["Proc: Rage/Energy gain avg to 30 AP"] = "Proc: Rage/Energy gain avg to 30 AP"
L["Use: 53 Avg AP"] = "Use: 53 Avg AP"
L["Proc: 340 AP (10s duration)"] = "Proc: 340 AP (10s duration)"
L["Use: 300 Spirit"] = "Use: 300 Spirit"
L["Use: 130 SP"] = "Use: 130 SP"
L["Use: 145 Dodge"] = "Use: 145 Dodge"
L["Proc: 130 SP"] = "Proc: 130 SP"
L["Use: 175 Haste"] = "Use: 175 Haste"
L["Use: 320 Haste (Decaying)"] = "Use: 320 Haste (Decaying)"
L["Use: 211 SP"] = "Use: 211 SP"
L["Use: 360 AP"] = "Use: 360 AP"
L["Use: 260 Haste"] = "Use: 260 Haste"
L["Use: 1750 HP"] = "Use: 1750 HP"
L["Use: 2000 Armor (Valued as defensive)"] = "Use: 2000 Armor (Valued as defensive)"
L["Proc: 152 Dodge"] = "Proc: 152 Dodge"
L["Use: Sustain"] = "Use: Sustain"
L["Use: ~23 Avg SP"] = "Use: ~23 Avg SP"
L["Proc: ~22 Avg SP"] = "Proc: ~22 Avg SP"
L["Proc: Heal Stacks avg to 49 Heal"] = "Proc: Heal Stacks avg to 49 Heal"
L["Proc: 152 Dodge for 10s (Low rate) = ~25 Avg"] = "Proc: 152 Dodge for 10s (Low rate) = ~25 Avg"
L["Passive: Resistances not valued"] = "Passive: Resistances not valued"
L["Proc: 1.33% Proc @ 70 (Nerfed in TBC)"] = "Proc: 1.33% Proc @ 70 (Nerfed in TBC)"
L["Use: 29 Avg SP"] = "Use: 29 Avg SP"
L["Use: Decaying stacks avg to ~34 SP"] = "Use: Decaying stacks avg to ~34 SP"
L["Use: 16.6 Avg Haste"] = "Use: 16.6 Avg Haste"
L["Use: 43 Avg AP"] = "Use: 43 Avg AP"
L["Use: 33 Avg Haste"] = "Use: 33 Avg Haste"
L["Proc: ArP"] = "Proc: ArP"
L["Passive: 25.2 Hit"] = "Passive: 25.2 Hit"
L["Use: 450 Heal (Decaying)"] = "Use: 450 Heal (Decaying)"
L["Use: 260 Def"] = "Use: 260 Def"
L["Use: 235 Block"] = "Use: 235 Block"
L["Use: AP (Stacking)"] = "Use: AP (Stacking)"
L["Proc: Dmg"] = "Proc: Dmg"
L["Use: Absorb"] = "Use: Absorb"
L["Use: Threat Drop"] = "Use: Threat Drop"
L["Use: Heal/Shield"] = "Use: Heal/Shield"
L["Use: 280 AP"] = "Use: 280 AP"
L["Use: 330 Haste"] = "Use: 330 Haste"
L["Use: Mana"] = "Use: Mana"
L["Use: 1500 HP"] = "Use: 1500 HP"
L["Use: Poison Dmg"] = "Use: Poison Dmg"
L["Use: 250 SP"] = "Use: 250 SP"
L["Use: 250 SP (Hunter)"] = "Use: 250 SP (Hunter)"
L["Passive: 2% Legacy Crit converts to 28 Rating"] = "Passive: 2% Legacy Crit converts to 28 Rating"
L["Passive: 2% Legacy Spell Crit converts to 28 Rating"] = "Passive: 2% Legacy Spell Crit converts to 28 Rating"
L["Passive: Weighted average vs Undead/Demon"] = "Passive: Weighted average vs Undead/Demon"
L["Proc: Cannon dmg avg to ~10 AP"] = "Proc: Cannon dmg avg to ~10 AP"
L["Proc: 25 Stats with ~33% uptime"] = "Proc: 25 Stats with ~33% uptime"
L["Proc: Dmg reduction value avg to Stam"] = "Proc: Dmg reduction value avg to Stam"
L["Passive: 29 SP"] = "Passive: 29 SP"
L["Use: Dmg/Heal"] = "Use: Dmg/Heal"
L["Passive: Max Stacks (120 AP / 80 SP)"] = "Passive: Max Stacks (120 AP / 80 SP)"
L["Proc: Holy Dmg avg to ~10 AP"] = "Proc: Holy Dmg avg to ~10 AP"
L["Passive: 51 Stamina Base"] = "Passive: 51 Stamina Base"
L["Proc: 100% Regen (Blue Dragon) avg to 60mp5"] = "Proc: 100% Regen (Blue Dragon) avg to 60mp5"
L["Use: SP"] = "Use: SP"
L["Use: 36.6 Avg AP"] = "Use: 36.6 Avg AP"
L["Use: Health valued as Defense"] = "Use: Health valued as Defense"
L["Use: ~23 Avg SP"] = "Use: ~23 Avg SP"
L["Use: 1000 HP (Shared CD)"] = "Use: 1000 HP (Shared CD)"
L["Use: Stun/Dmg utility"] = "Use: Stun/Dmg utility"
L["Use: Haste"] = "Use: Haste"
L["Use: HP"] = "Use: HP"
L["Use: Avg 20 BV"] = "Use: Avg 20 BV"
L["Use: 265 Heal"] = "Use: 265 Heal"
L["Use: Shield"] = "Use: Shield"
L["Use: Block value avg to 20"] = "Use: Block value avg to 20"
L["Use: Dmg"] = "Use: Dmg"
L["Use: Pet"] = "Use: Pet"
L["Use: Poly"] = "Use: Poly"
L["Proc: Extra Swing value avg to 30 AP"] = "Proc: Extra Swing value avg to 30 AP"
L["Use: 50% Haste - Burst Value"] = "Use: 50% Haste - Burst Value"
L["Powershift: Energy Refund valued as 80 AP"] = "Powershift: Energy Refund valued as 80 AP"
L["Passive: 85 SP vs Demon/Undead"] = "Passive: 85 SP vs Demon/Undead"
L["Passive: 150 AP vs Demon/Undead"] = "Passive: 150 AP vs Demon/Undead"

-- =============================================================
-- Data_sets
-- =============================================================

-- PROC & SET BONUS NOTES
L["Chance on hit: Haste"] = "Chance on hit: Haste"
L["ERA BiS for Melee (HoJ)"] = "ERA BiS for Melee (HoJ)"
L["ERA BiS Caster (Nelth's Tear)"] = "ERA BiS Caster (Nelth's Tear)"
L["ERA BiS Physical (DFT)"] = "ERA BiS Physical (DFT)"
L["Legendary Threat Gen (TF)"] = "Legendary Threat Gen (TF)"
L["ERA Top Tier Prot Pally"] = "ERA Top Tier Prot Pally"
L["Bladestorm Proc"] = "Bladestorm Proc"
L["BiS Physical"] = "BiS Physical"
L["Moroes' Watch (Dodge Use)"] = "Moroes' Watch (Dodge Use)"
L["Talisman of Tenacity (Use: HP)"] = "Talisman of Tenacity (Use: HP)"
L["Pet Proc"] = "Pet Proc"
L["Rage/Energy Proc"] = "Rage/Energy Proc"
L["BiS (Infinite Energy Proc)"] = "BiS (Infinite Energy Proc)"
L["BiS Tank (Proc)"] = "BiS Tank (Proc)"
L["BiS Hunter (Mana Proc)"] = "BiS Hunter (Mana Proc)"
L["BiS (Mechanic)"] = "BiS (Mechanic)"
L["LEGENDARY"] = "LEGENDARY"
L["Stun Proc PvP BiS"] = "Stun Proc PvP BiS"

-- =============================================================
-- JUDGE
-- =============================================================
L["Classic Era"] = "Classic Era"
L["TBC Edition"] = "TBC Edition"
L["|cff00ff00Sharpie's Gear Judge|r (%s) Loaded. Type /sgj for menu."] = "|cff00ff00Sharpie's Gear Judge|r (%s) Loaded. Type /sgj for menu."
L["|cffffd100SGJ Warning:|r 'Pawn' is loaded. Tooltips may look cluttered."] = "|cffffd100SGJ Warning:|r 'Pawn' is loaded. Tooltips may look cluttered."
L["|cffffd100SGJ Warning:|r 'Zygor' detected. Ensure its item scoring is disabled."] = "|cffffd100SGJ Warning:|r 'Zygor' detected. Ensure its item scoring is disabled."

-- Popups
L["|cff00ccffSharpie's Gear Judge|r\n\nProfile imported successfully!\n\nYou must reload your UI for the changes to take effect."] = "|cff00ccffSharpie's Gear Judge|r\n\nProfile imported successfully!\n\nYou must reload your UI for the changes to take effect."
L["Reload Now"] = "Reload Now"
L["Later"] = "Later"

-- Tooltip Headers
L["Judge's Score:"] = "Judge's Score:"
L["Verdict Profile:"] = "Verdict Profile:"
L["Capped"] = "Capped"
L["|cff00ffff* EQUIPPED *|r"] = "|cff00ffff* EQUIPPED *|r"
L["vs."] = "vs."
L["Judge's Note:"] = "Judge's Note:"
L["Class Bonus: "] = "Class Bonus: "

-- Upgrade/Downgrade Text
-- Note: %s is the Texture, %.1f are numbers
L["|cff00ff00%s Upgrade (+%.1f / +%.1f%%)|r"] = "|cff00ff00%s Upgrade (+%.1f / +%.1f%%)|r"
L["|cffff0000%s Downgrade (%.1f / %.1f%%)|r"] = "|cffff0000%s Downgrade (%.1f / %.1f%%)|r"
L["|cff888888= Sidegrade (0.0)|r"] = "|cff888888= Sidegrade (0.0)|r"

-- Warnings
L["|cffff0000!!! WARNING: Breaking Set Bonus (%d) !!!|r"] = "|cffff0000!!! WARNING: Breaking Set Bonus (%d) !!!|r"
L["|cff00ff00+++ GAINED: %d-pc Set Bonus! +++|r"] = "|cff00ff00+++ GAINED: %d-pc Set Bonus! +++|r"
L["  |cffff0000(Breaks %d-pc Set Bonus!)|r"] = "  |cffff0000(Breaks %d-pc Set Bonus!)|r"
L["|cff00ff00+%s (Upgrade)|r"] = "|cff00ff00+%s (Upgrade)|r"

-- Projections
L["Projected Enchant:"] = "Projected Enchant:"
L["Best Available"] = "Best Available"
L["Projected Gems:"] = "Projected Gems:"
L["+ Meta Gem Active"] = "+ Meta Gem Active"
L["- Meta Gem Inactive (Reqs unmet)"] = "- Meta Gem Inactive (Reqs unmet)"

-- Lists
L["Gains:"] = "Gains:"
L["Losses:"] = "Losses:"

-- [[ INTERFACE: VISUALS ]]
L["Tooltip Visuals"] = "Tooltip Visuals"
L["Compact Equip Text"] = "Compact Equip Text"
L["Compact Equip Tooltip"] = "Rewrites long 'Equip' sentences into concise math.\n\nExample:\n'Equip: Increases your hit rating by 20.'\nbecomes\n'Equip: +20 Hit'"
L["Shorten Stat Names"] = "Shorten Stat Names"
L["Shorten Stat Tooltip"] = "Abbreviates stat names to save space.\n\nExamples:\nStrength > Str\nAttack Power > AP"
L["Colorize Stats"] = "Colorize Stats"
L["Colorize Stats Tooltip"] = "Applies colors to stats."

-- =============================================================
-- DYNAMIC ENGINE
-- =============================================================
L["Auto: %s"] = "Auto: %s"

-- =============================================================
-- INTERFACE (Lab, Receipt, Settings)
-- =============================================================
-- Stat Logic Tooltips

L["Need %d more rating to cap."] = "Need %d more rating to cap."
L["Cap reached!"] = "Cap reached!"
L["Current Rating:"] = "Current Rating:"
L["1%% requires %.2f Rating"] = "1%% requires %.2f Rating"
L["Gear Contribution:"] = "Gear Contribution:"
L["Character Sheet:"] = "Character Sheet:"
L["%d (Includes Base/Enchants)"] = "%d (Includes Base/Enchants)"
L["Score Calculation:"] = "Score Calculation:"
L["%.2f (Weight) x %.1f (Gear)"] = "%.2f (Weight) x %.1f (Gear)"
L["Stat Weight:"] = "Stat Weight:"
L["You currently have 0 of this stat from gear."] = "You currently have 0 of this stat from gear."

-- Misc
L["Laboratory"] = "Laboratory"
L["Select..."] = "Select..."
L["(Empty)"] = "(Empty)"
L["Weapon Thunderdome"] = "Weapon Thunderdome"
L["Receipt"] = "Receipt"
L["Stat Logic"] = "Stat Logic"
L["Rating:"] = "Rating:"
L["Protocol"] = "Protocol"
L["Drag (Shift/Ctrl+Click) items to compare. 6 Sets Enter, 1 Set Wins!"] = "Drag (Shift/Ctrl+Click) items to compare. 6 Sets Enter, 1 Set Wins!"
L["Option A1: Two-Hander"] = "Option A1: Two-Hander"
L["Option B1: 1H + Shield/OH"] = "Option B1: 1H + Shield/OH"
L["Option C1: Dual Wield"] = "Option C1: Dual Wield"
L["Option A2: Two-Hander"] = "Option A2: Two-Hander"
L["Option B2: 1H + Shield/OH"] = "Option B2: 1H + Shield/OH"
L["Option C2: Dual Wield"] = "Option C2: Dual Wield"
L["Waiting for Items..."] = "Waiting for Items..."
L["Option A1 (2H)"] = "Option A1 (2H)"
L["Option B1 (1H+OH)"] = "Option B1 (1H+OH)"
L["Option C1 (DW)"] = "Option C1 (DW)"
L["Option A2 (2H)"] = "Option A2 (2H)"
L["Option B2 (1H+OH)"] = "Option B2 (1H+OH)"
L["Option C2 (DW)"] = "Option C2 (DW)"
L["%s Wins! (+%s)"] = "%s Wins! (+%s)"

-- Receipt
L["ARMOR"] = "ARMOR"
L["ACCESSORIES"] = "ACCESSORIES"
L["WEAPONS"] = "WEAPONS"
L["Head"] = "Head"
L["Shoulder"] = "Shoulder"
L["Back"] = "Back"
L["Chest"] = "Chest"
L["Wrist"] = "Wrist"
L["Hands"] = "Hands"
L["Waist"] = "Waist"
L["Legs"] = "Legs"
L["Feet"] = "Feet"
L["Neck"] = "Neck"
L["Ring 1"] = "Ring 1"
L["Ring 2"] = "Ring 2"
L["Trinket 1"] = "Trinket 1"
L["Trinket 2"] = "Trinket 2"
L["Main Hand"] = "Main Hand"
L["Off Hand"] = "Off Hand"
L["Ranged"] = "Ranged"
L["COMBINED GEAR STAT TOTALS"] = "COMBINED GEAR STAT TOTALS"
L["Score: "] = "Score: "
L["Missing Enchant!"] = "Missing Enchant!"
L["Better item in bags!"] = "Better item in bags!"

-- Settings
L["Comparison Logic"] = "Comparison Logic"
L["Enchant Mode"] = "Enchant Mode"
L["Off (Raw Stats)"] = "Off (Raw Stats)"
L["Current Only"] = "Current Only"
L["Project Best"] = "Project Best"
L["Controls how item enchantments affect the score.\n\n|cffffffffOff:|r Scores items based on base stats only.\n|cffffffffCurrent:|r Includes the value of the enchant currently on the item.\n|cffffffffProject:|r Simulates the best possible enchant for that item level."] = "Controls how item enchantments affect the score.\n\n|cffffffffOff:|r Scores items based on base stats only.\n|cffffffffCurrent:|r Includes the value of the enchant currently on the item.\n|cffffffffProject:|r Simulates the best possible enchant for that item level."

L["Gemming Logic"] = "Gemming Logic"
L["The Skeptic"] = "The Skeptic"
L["The Casual"] = "The Casual"
L["The Pro"] = "The Pro"
L["Controls how empty sockets are scored.\n\n|cffffffffSkeptic:|r Empty sockets are worth 0. Socket bonuses are ignored unless fully met.\n|cffffffffCasual:|r Assumes empty sockets are filled with Rare (Blue) quality gems.\n|cffffffffPro:|r Assumes empty sockets are filled with Epic/Best-in-Slot gems."] = "Controls how empty sockets are scored.\n\n|cffffffffSkeptic:|r Empty sockets are worth 0. Socket bonuses are ignored unless fully met.\n|cffffffffCasual:|r Assumes empty sockets are filled with Rare (Blue) quality gems.\n|cffffffffPro:|r Assumes empty sockets are filled with Epic/Best-in-Slot gems."

L["Character Profile"] = "Character Profile"
L["Auto-Detect"] = "Auto-Detect"
L["Active Scoring Profile"] = "Active Scoring Profile"
L["Manually override the scoring profile.\n\n|cffffffffAuto-Detect:|r Automatically selects a profile based on your talents and recent gameplay.\n\nSelecting a specific profile forces the addon to judge all gear for that spec, regardless of your current talents."] = "Manually override the scoring profile.\n\n|cffffffffAuto-Detect:|r Automatically selects a profile based on your talents and recent gameplay.\n\nSelecting a specific profile forces the addon to judge all gear for that spec, regardless of your current talents."

L["Interface Options"] = "Interface Options"
L["Hide Minimap Button"] = "Hide Minimap Button"
L["Hides the circular button on your minimap."] = "Hides the circular button on your minimap."
L["Hide Tooltip Verdict"] = "Hide Tooltip Verdict"
L["Stops the addon from adding scores to item tooltips."] = "Stops the addon from adding scores to item tooltips."
L["Show Only via Shift Key"] = "Show Only via Shift Key"
L["Only shows the Judge score in tooltips while holding the SHIFT key."] = "Only shows the Judge score in tooltips while holding the SHIFT key."
L["Mute Error Sounds"] = "Mute Error Sounds"
L["Stops the error sound when clicking invalid items."] = "Stops the error sound when clicking invalid items."
L["Disable Conflict Check"] = "Disable Conflict Check"
L["Stops the chat warning about Pawn/Zygor."] = "Stops the chat warning about Pawn/Zygor."

L["Secondary Spec Tracking"] = "Secondary Spec Tracking"
L["Select additional profiles to track in tooltips.\n\nIf an item is an upgrade for a checked profile, a small notification will appear at the bottom of the item tooltip."] = "Select additional profiles to track in tooltips.\n\nIf an item is an upgrade for a checked profile, a small notification will appear at the bottom of the item tooltip."

L["Import Pawn String"] = "Import Pawn String"
L["Export Data"] = "Export Data"
L["Paste Pawn string here..."] = "Paste Pawn string here..."
L["Import"] = "Import"
L["Export Data (Discord Ready)"] = "Export Data (Discord Ready)"
L["Unknown"] = "Unknown"
L["Unknown Item"] = "Unknown Item"
L["No Weights Loaded"] = "No Weights Loaded"
L["Total Score: "] = "Total Score: "
L["Scroll to Scale"] = "Scroll to Scale"
L["Hold\nto Move"] = "Hold\nto Move"

-- Stat Reasons
L["Increases Attack Power and Block Value"] = "Increases Attack Power and Block Value"
L["Increases Crit Chance, Dodge, and Armor"] = "Increases Crit Chance, Dodge, and Armor"
L["Increases total Health Pool"] = "Increases total Health Pool"
L["Increases Mana Pool and Spell Crit"] = "Increases Mana Pool and Spell Crit"
L["Increases Out-of-Combat and Spell5 Regen"] = "Increases Out-of-Combat and Spell5 Regen"
L["Increases Raw Physical Damage Output"] = "Increases Raw Physical Damage Output"
L["Reduces chance Target Parries or Dodges"] = "Reduces chance Target Parries or Dodges"
L["Ignores a portion of Target's Armor"] = "Ignores a portion of Target's Armor"
L["Reduces chance to Miss Physical attacks"] = "Reduces chance to Miss Physical attacks"
L["Increases Scaling Damage of Spells"] = "Increases Scaling Damage of Spells"
L["Increases Potency of Healing spells"] = "Increases Potency of Healing spells"
L["Reduces chance for Spells to Resist/Miss"] = "Reduces chance for Spells to Resist/Miss"
L["Constant Mana Sustain (Mp5)"] = "Constant Mana Sustain (Mp5)"
L["Chance for Extra Critical Damage/Healing"] = "Chance for Extra Critical Damage/Healing"
L["Increases Attack/Casting Speed"] = "Increases Attack/Casting Speed"
L["Reduces chance to be Crit and Hit"] = "Reduces chance to be Crit and Hit"
L["Chance to completely Avoid Physical attacks"] = "Chance to completely Avoid Physical attacks"
L["Chance to Deflect front-facing attacks"] = "Chance to Deflect front-facing attacks"
L["Increases Damage mitigated by Shield"] = "Increases Damage mitigated by Shield"
L["Chance to Mitigate damage with Shield"] = "Chance to Mitigate damage with Shield"
L["Reduces Crit Damage and Chance (PvP)"] = "Reduces Crit Damage and Chance (PvP)"
L["Reduces Incoming Physical Damage"] = "Reduces Incoming Physical Damage"

-- =============================================================
-- HELPERS & DEBUG
-- =============================================================
L["|cffff0000SGJ: Invalid Pawn string format or empty stats.|r"] = "|cffff0000SGJ: Invalid Pawn string format or empty stats.|r"
L["|cff00ff00SGJ:|r Successfully imported %s"] = "|cff00ff00SGJ:|r Successfully imported %s"

L["|cffff0000SGJ: Please hover over an item to debug.|r"] = "|cffff0000SGJ: Please hover over an item to debug.|r"
L["|cffff0000SGJ: No weights loaded.|r"] = "|cffff0000SGJ: No weights loaded.|r"
L["|cff00ccff--- SGJ DEBUG REPORT ---|r"] = "|cff00ccff--- SGJ DEBUG REPORT ---|r"
L["Item: "] = "Item: "
L["Profile: "] = "Profile: "
L["|cffffffff%s:|r %.1f x %.2f = |cff00ff00%.1f|r"] = "|cffffffff%s:|r %.1f x %.2f = |cff00ff00%.1f|r"
L["|cff888888%s: %.1f (Weight: 0)|r"] = "|cff888888%s: %.1f (Weight: 0)|r"
L["Ratio Check: "] = "Ratio Check: "
L["Useful: %.1f / Useless: %.1f"] = "Useful: %.1f / Useless: %.1f"
L["|cffff0000[FAIL] Item rejected by Bouncer (Mostly Junk)|r"] = "|cffff0000[FAIL] Item rejected by Bouncer (Mostly Junk)|r"
L["|cff00ff00[PASS] Item accepted|r"] = "|cff00ff00[PASS] Item accepted|r"
L["Final Score: "] = "Final Score: "

-- =============================================================
-- PARSER: KEYWORDS & PATTERNS
-- =============================================================
-- Classify Keywords
L["equip"] = "equip"
L["use:"] = "use:"
L["chance on"] = "chance on"
L["set:"] = "set:"
L["socket"] = "socket"
L["bonus"] = "bonus"
L["spell"] = "spell"
L["hit"] = "hit"
L["crit"] = "crit"
L["speed"] = "speed"
L["haste"] = "haste"
L["armor"] = "armor"
L["^to "] = "^to "
L["^equip: "] = "^equip: "

-- Header Patterns
L["^(.*)%s+%(?(%d+)/(%d+)%)?$"] = "^(.*)%s+%(?(%d+)/(%d+)%)?$"
L["^%s*equip:%s*"] = "^%s*equip:%s*"
L["^chance on hit: "] = "^chance on hit: "
L["^equip: chance on hit: "] = "^equip: chance on hit: "
L["^use: "] = "^use: "

-- Stat Patterns (Regex)
L["^[%+]?%s*(%d+%.?%d*)%s+(.-)[%s%.]*$"] = "^[%+]?%s*(%d+%.?%d*)%s+(.-)[%s%.]*$"
L["^(.-)%s+[%+:]?%s*(%d+%.?%d*)[%s%.]*$"] = "^(.-)%s+[%+:]?%s*(%d+%.?%d*)[%s%.]*$"
L["^(%d+) armor$"] = "^(%d+) armor$"
L["^(%d+) block$"] = "^(%d+) block$"
L["speed (%d+%.?%d*)"] = "speed (%d+%.?%d*)"
L["^%((%d+%.?%d*) damage per second%)$"] = "^%((%d+%.?%d*) damage per second%)$"
L["^%((%d+%.?%d*) dps%)$"] = "^%((%d+%.?%d*) dps%)$"
L["^(%d+)%s?[-~]%s?(%d+) damage$"] = "^(%d+)%s?[-~]%s?(%d+) damage$"
L["scope %([%+:]*(%d+) (.*)%)"] = "scope %([%+:]*(%d+) (.*)%)"
L["enchant:? [%+:]*(%d+) (.*)"] = "enchant:? [%+:]*(%d+) (.*)"

-- Equip/Use/Proc Patterns (English Defaults)
L["damage and healing.-(%d+)"] = "damage and healing.-(%d+)"
L["healing done.-(%d+)"] = "healing done.-(%d+)"
L["spell penetration.-(%d+)"] = "spell penetration.-(%d+)"
L["restores (%d+) mana"] = "restores (%d+) mana"
L["spell hit rating.-(%d+)"] = "spell hit rating.-(%d+)"
L["ranged hit rating.-(%d+)"] = "ranged hit rating.-(%d+)"
L["hit rating.-(%d+)"] = "hit rating.-(%d+)"
L["spell crit.-(%d+)"] = "spell crit.-(%d+)"
L["ranged crit.-(%d+)"] = "ranged crit.-(%d+)"
L["critical strike rating.-(%d+)"] = "critical strike rating.-(%d+)"
L["ranged attack power.-(%d+)"] = "ranged attack power.-(%d+)"
L["feral attack power.-(%d+)"] = "feral attack power.-(%d+)"
L["attack power.-(%d+)"] = "attack power.-(%d+)"
L["expertise rating.-(%d+)"] = "expertise rating.-(%d+)"
L["armor penetration.-(%d+)"] = "armor penetration.-(%d+)"
L["block value.-(%d+)"] = "block value.-(%d+)"
L["block rating.-(%d+)"] = "block rating.-(%d+)"
L["defense rating.-(%d+)"] = "defense rating.-(%d+)"
L["dodge rating.-(%d+)"] = "dodge rating.-(%d+)"
L["parry rating.-(%d+)"] = "parry rating.-(%d+)"
L["resilience.-(%d+)"] = "resilience.-(%d+)"
L["spell haste.-(%d+)"] = "spell haste.-(%d+)"
L["haste rating.-(%d+)"] = "haste rating.-(%d+)"
L["shadow damage.-(%d+)"] = "shadow damage.-(%d+)"
L["fire damage.-(%d+)"] = "fire damage.-(%d+)"
L["frost damage.-(%d+)"] = "frost damage.-(%d+)"
L["arcane damage.-(%d+)"] = "arcane damage.-(%d+)"
L["nature damage.-(%d+)"] = "nature damage.-(%d+)"
L["holy damage.-(%d+)"] = "holy damage.-(%d+)"
L["healing.-up to (%d+).-damage.-up to (%d+)"] = "healing.-up to (%d+).-damage.-up to (%d+)"
L["adds (%d+) weapon damage"] = "adds (%d+) weapon damage"
L["adds (%d+) damage"] = "adds (%d+) damage"
L["improves your (.*) by (%d+)%%%.?"] = "improves your (.*) by (%d+)%%%.?"
L["increases your (.*) by (%d+)%%%.?"] = "increases your (.*) by (%d+)%%%.?"
L["increases (.*) by (%d+)%%%.?"] = "increases (.*) by (%d+)%%%.?"
L["improves your (.*) by (%d+)%.?"] = "improves your (.*) by (%d+)%.?"
L["improves (.*) by (%d+)%.?"] = "improves (.*) by (%d+)%.?"
L["increases your (.*) by (%d+)%.?"] = "increases your (.*) by (%d+)%.?"
L["increases (.*) by up to (%d+)%.?"] = "increases (.*) by up to (%d+)%.?"
L["increases (.*) by (%d+)%.?"] = "increases (.*) by (%d+)%.?"
L["^%+?%s*(%d+)%%? (.*)$"] = "^%+?%s*(%d+)%%? (.*)$"
L["^(.-) %+(%d+)%%?$"] = "^(.-) %+(%d+)%%?$"
L["^%+(%d+) (.*) for (%d+) sec"] = "^%+(%d+) (.*) for (%d+) sec"
L["grants (%d+) (.*) for (%d+) sec"] = "grants (%d+) (.*) for (%d+) sec"
L["gain (%d+) (.*) for (%d+) sec"] = "gain (%d+) (.*) for (%d+) sec"
L["increases (.*) by (%d+) for (%d+) sec"] = "increases (.*) by (%d+) for (%d+) sec"
L["increases your (.*) by (%d+)$"] = "increases your (.*) by (%d+)$"
L["chance on melee or ranged hit to gain (%d+) (.*) for (%d+) sec"] = "chance on melee or ranged hit to gain (%d+) (.*) for (%d+) sec"
L["chance on spell critical hit to gain (%d+) (.*) for (%d+) sec"] = "chance on spell critical hit to gain (%d+) (.*) for (%d+) sec"
L["chance on spell cast to gain (%d+) (.*) for (%d+) sec"] = "chance on spell cast to gain (%d+) (.*) for (%d+) sec"
L["for (%d+) to (%d+) .*damage"] = "for (%d+) to (%d+) .*damage"
L["inflicts (%d+) to (%d+) .*damage"] = "inflicts (%d+) to (%d+) .*damage"
L["for (%d+) .*damage"] = "for (%d+) .*damage"
L["inflicts (%d+) .*damage"] = "inflicts (%d+) .*damage"
L["deals (%d+) .*damage"] = "deals (%d+) .*damage"
L["blasts (.*) for (%d+)"] = "blasts (.*) for (%d+)"
L["chance to strike your enemy for (%d+) to (%d+) .*damage"] = "chance to strike your enemy for (%d+) to (%d+) .*damage"
L["chance to blast your target for (%d+) to (%d+) .*damage"] = "chance to blast your target for (%d+) to (%d+) .*damage"
L["steals (%d+) life"] = "steals (%d+) life"
L["restores (%d+) health"] = "restores (%d+) health"
L["blasts your enemy"] = "blasts your enemy"
L["^%+(%d+) (.*)$"] = "^%+(%d+) (.*)$"
L["increases (.*) by up to (%d+) for (%d+) sec"] = "increases (.*) by up to (%d+) for (%d+) sec"
L["restores (%d+) to (%d+) mana"] = "restores (%d+) to (%d+) mana"
L["restores (%d+) to (%d+) health"] = "restores (%d+) to (%d+) health"

-- Data Map Keys (Standard)
L["strength"] = "strength"
L["agility"] = "agility"
L["stamina"] = "stamina"
L["intellect"] = "intellect"
L["spirit"] = "spirit"
L["armor"] = "armor"
L["block"] = "block"
L["block value"] = "block value"
L["speed"] = "speed"
L["damage per second"] = "damage per second"
L["dps"] = "dps"
L["shadow resistance"] = "shadow resistance"
L["fire resistance"] = "fire resistance"
L["frost resistance"] = "frost resistance"
L["arcane resistance"] = "arcane resistance"
L["nature resistance"] = "nature resistance"
L["attack power"] = "attack power"
L["healing spells"] = "healing spells"
L["healing"] = "healing"
L["spell damage"] = "spell damage"
L["spell power"] = "spell power"
L["shadow damage"] = "shadow damage"
L["fire damage"] = "fire damage"
L["frost damage"] = "frost damage"
L["arcane damage"] = "arcane damage"
L["nature damage"] = "nature damage"
L["holy damage"] = "holy damage"
L["shadow spell damage"] = "shadow spell damage"
L["fire spell damage"] = "fire spell damage"
L["frost spell damage"] = "frost spell damage"
L["arcane spell damage"] = "arcane spell damage"
L["nature spell damage"] = "nature spell damage"
L["holy spell damage"] = "holy spell damage"
L["spell damage and healing"] = "spell damage and healing"
L["damage and healing spells"] = "damage and healing spells"
L["ranged attack power"] = "ranged attack power"
L["spell penetration"] = "spell penetration"
L["all stats"] = "all stats"
L["magic resistance"] = "magic resistance"
L["mana"] = "mana"
L["health"] = "health"
L["hp"] = "hp"
L["mp"] = "mp"
L["dodge rating"] = "dodge rating"
L["parry rating"] = "parry rating"
L["block rating"] = "block rating"
L["hit rating"] = "hit rating"
L["crit rating"] = "crit rating"
L["critical strike rating"] = "critical strike rating"
L["haste rating"] = "haste rating"
L["resilience rating"] = "resilience rating"
L["defense rating"] = "defense rating"
L["expertise rating"] = "expertise rating"
L["armor penetration rating"] = "armor penetration rating"

-- Green Text Map Keys
L["chance to hit"] = "chance to hit"
L["chance to get a critical strike"] = "chance to get a critical strike"
L["spell hit rating"] = "spell hit rating"
L["chance to hit with spells"] = "chance to hit with spells"
L["spell critical strike rating"] = "spell critical strike rating"
L["critical strike with spells"] = "critical strike with spells"
L["chance to get a critical strike with spells"] = "chance to get a critical strike with spells"
L["spell haste rating"] = "spell haste rating"
L["magical resistances"] = "magical resistances"
L["magical resistances of your spell targets"] = "magical resistances of your spell targets"
L["increased defense"] = "increased defense"
L["defense"] = "defense"
L["chance to dodge"] = "chance to dodge"
L["chance to parry"] = "chance to parry"
L["chance to block"] = "chance to block"
L["shield block value"] = "shield block value"
L["the block value of your shield"] = "the block value of your shield"
L["all resistances"] = "all resistances"
L["resistance to all schools of magic"] = "resistance to all schools of magic"
L["attack power in cat"] = "attack power in cat"
L["feral attack power"] = "feral attack power"
L["mana per 5 sec"] = "mana per 5 sec"
L["health per 5 sec"] = "health per 5 sec"
L["healing done by spells and effects"] = "healing done by spells and effects"
L["healing done by magical spells and effects"] = "healing done by magical spells and effects"
L["spell damage rating"] = "spell damage rating"
L["damage done by magical spells and effects"] = "damage done by magical spells and effects"
L["damage and healing done by magical spells and effects"] = "damage and healing done by magical spells and effects"
L["damage and healing done by magical spells and effects by up to"] = "damage and healing done by magical spells and effects by up to"
L["damage done by shadow spells and effects"] = "damage done by shadow spells and effects"
L["damage done by fire spells and effects"] = "damage done by fire spells and effects"
L["damage done by frost spells and effects"] = "damage done by frost spells and effects"
L["damage done by arcane spells and effects"] = "damage done by arcane spells and effects"
L["damage done by nature spells and effects"] = "damage done by nature spells and effects"
L["damage done by holy spells and effects"] = "damage done by holy spells and effects"
L["swords"] = "swords"
L["axes"] = "axes"
L["maces"] = "maces"
L["daggers"] = "daggers"
L["bows"] = "bows"
L["crossbows"] = "crossbows"
L["guns"] = "guns"
L["staves"] = "staves"
L["polearms"] = "polearms"
L["two-handed swords"] = "two-handed swords"
L["two-handed axes"] = "two-handed axes"
L["two-handed maces"] = "two-handed maces"
L["skill with swords"] = "skill with swords"
L["skill with axes"] = "skill with axes"
L["skill with maces"] = "skill with maces"
L["skill with bows"] = "skill with bows"
L["skill with guns"] = "skill with guns"
L["skill with daggers"] = "skill with daggers"
L["skill with crossbows"] = "skill with crossbows"
L["skill with staves"] = "skill with staves"
L["skill with polearms"] = "skill with polearms"
L["ranged critical strike rating"] = "ranged critical strike rating"
L["ranged hit rating"] = "ranged hit rating"
L["ranged haste rating"] = "ranged haste rating"
L["shield block rating"] = "shield block rating"
L["your pet's armor"] = "your pet's armor"
L["your pet's attack power"] = "your pet's attack power"
L["your pet's damage"] = "your pet's damage"
L["chance to resist mechanic mechanics"] = "chance to resist mechanic mechanics"
L["^(.*)%s+%(?(%d+)/(%d+)%)?$"] = "^(.*)%s+%(?(%d+)/(%d+)%)?$"